carla-simulator/scenario_runner

.gitignore, README.md, ScenarioManager/atomic_scenario_behavior.py, ScenarioManager/atomic_scenario_criteria.py, ScenarioManager/scenario_manager.py, follow_vehicle_scenario.py, manual_control.py
This commit adds basic scenario execution capabilities for Carla.
Scenarios (the behavior and the evaluation criteria) are defined with
the help of py_trees. The execution of the scenario and the final result
analysis is performed via a ScenerioManager.
Current Features:
- Initial set of atomic behaviors required for defining a scenario:
* Accelerate to target velocity
* Keep target velocity for certain amount of time
* Stop vehicle
* Trigger a scenario action by entering a region on a map
* Trigger a scenario action by reaching a certain distance to another
actor
- Initial set of atomic evaluation criteria for scenarios:
* Check collision count
* Check times the vehicle entered another lane
* Check speed limit
- Scenario class implements the complete scenario behavior and evaluation
set …
=> Added initial implementation for ScenarioManager and scenario handling

README.md, ScenarioManager/atomic_scenario_behavior.py, ScenarioManager/atomic_scenario_criteria.py, ScenarioManager/carla_data_provider.py, ScenarioManager/result_writer.py, ScenarioManager/scenario_manager.py, ScenarioManager/timer.py, Scenarios/follow_leading_vehicle.py, follow_vehicle_scenario.py, scenario_runner.py
This pull request brings in various new features for the ScenarioManager:
- Usage of CARLA game time
- Additional atomic behaviors
- time-to-arrival behavior (for location and vehicle)
- trigger distance to target location behavior
- trigger velocity behavior
- Additonal evaluation criteria
- Average velocity
- Driven distance
- Logger for output data (stdout, human-readable test file, junit xml)
- Created module (Scenarios/) for complete scenarios. First one in there: Following leading vehicle
- Handling of scenario repetitions
Tested with:
[x] CARLA 0.9.1
[x] Ubuntu 16.04
[x] FollowLeadingVehicle scenario
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/2) …
=> Enhancements for ScenarioManager

.gitignore, Docs/CODE_OF_CONDUCT.md, Docs/CONTRIBUTING.md, Docs/coding_standard.md, Docs/creating_new_scenario.md, Docs/getting_started.md, README.md, ScenarioManager/atomic_scenario_behavior.py, ScenarioManager/carla_data_provider.py, ScenarioManager/scenario_manager.py, ScenarioManager/timer.py, Scenarios/basic_scenario.py, Scenarios/follow_leading_vehicle.py, manual_control.py, scenario_runner.py
Various updates for the scenario runner and manager:
- Remove callbacks for GameTime and CarlaDataProvider
- New atomic behaviors: DriveDistance and UseAutoPilot
- Reworked FollowLeadingVehicle for CARLA challenge
- Make use of hero vehicle identification
Tested with:
[x] CARLA 0.9.1 (has to include commit: bc5a3ed)
[x] Ubuntu 16.04
[x] FollowLeadingVehicle and FollowLeadingVehicleWithObstacle scenario
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/4)
=> Various updates for the scenario runner and manager

.pylintrc, Docs/getting_started.md, ScenarioManager/atomic_scenario_behavior.py, ScenarioManager/atomic_scenario_criteria.py, ScenarioManager/carla_data_provider.py, ScenarioManager/result_writer.py, ScenarioManager/scenario_manager.py, ScenarioManager/timer.py, Scenarios/basic_scenario.py, Scenarios/follow_leading_vehicle.py, Utilities/code_check_and_formatting.sh, scenario_runner.py
- Use leading _ for private class members in Python
- Added script to format and check python code
- Updated FollowLeadingVehicleWithObstacle scenario to use fixed vehicles (T2 bus and bicycle)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/8)
=> Update code formatting

.vscode/settings.json, ScenarioManager/atomic_scenario_behavior.py, Scenarios/object_crash_vehicle.py, scenario_runner.py
1. Added New scenarios StationaryObjectCrash and DynamicObjectCrash in Scenario object_crash_vehicle.py
2. Modified scenario_runner.py to run new scenario.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/6)
=> Implementation of Traffic Scenario 03

Docs/creating_new_scenario.md, Docs/getting_started.md, Docs/list_of_scenarios.md, ScenarioManager/atomic_scenario_behavior.py, ScenarioManager/atomic_scenario_criteria.py, ScenarioManager/carla_data_provider.py, ScenarioManager/result_writer.py, ScenarioManager/scenario_manager.py, ScenarioManager/timer.py, Scenarios/basic_scenario.py, Scenarios/follow_leading_vehicle.py, Scenarios/object_crash_vehicle.py, Scenarios/opposite_vehicle_taking_priority.py, scenario_runner.py
Some small polishing:
[x] Updated copyright notice in python files 
[x] Fixed reporting of timeout result of a scenario run
[x] Cleanup of documentation for FollowLeadingVehicle
[x] Additional documentation on the currently supported scenarios
[x] Added version info to scenario_runner, to facilitate documentation (which scenario_runner requires which CARLA version, etc.)
And added Scenario07
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/11)
=> Some cleanup of ScenarioManager and Scenario07

Docs/pull_request_template.md, ScenarioManager/atomic_scenario_behavior.py, ScenarioManager/atomic_scenario_criteria.py, ScenarioManager/result_writer.py, ScenarioManager/scenario_manager.py, Scenarios/follow_leading_vehicle.py, Scenarios/opposite_vehicle_taking_priority.py
Changes:
[x] Added optional tag for scenario criteria
[x] Extended result range for scenario criteria to SUCCESS/ACCEPTABLE/FAILURE
--> Both of these features are implemented such that the existing scenarios do not need to be    updated!
[x] Extended FollowLeadingVehicle to show usage of the new features
[x] Updated scenario behavior when using vehicle control (enforce steering = 0, where necessary)
Others:
[x] Added pull_request_template 
[x] Use traffic light location not id for OppositeVehicleRunningRedLight
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/13)
=> Extended scenario criteria and few more updates

Scenarios/opposite_vehicle_taking_priority.py
Town03 was updated with a different traffic light setup (american style
instead of european style). The scenario was updated accordingly.
Checklist:
* **Platform(s):**  Ubuntu 16.04
* **Python version(s):** Python 2.7 and Python 3.5
* **Unreal Engine version(s):** 4.19
* **CARLA version:** pre_compiled: dc4a9d2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/14)
=> Updated Scenario07 to match Town03 updates

CHANGELOG.md, Docs/getting_started.md, Docs/pull_request_template.md, ScenarioManager/atomic_scenario_behavior.py
Checklist:
* **Platform(s):**  Ubuntu 16.04
* **Python version(s):** Python 2.7 and 3.5
* **Unreal Engine version(s):** 4.19
* **CARLA version:** 0.9.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/25)
=> Added BasicAgent as atomic behavior and updated documentation

.gitignore, .pylintrc, CHANGELOG.md, Configs/ControlLoss.xml, Configs/FollowLeadingVehicle.xml, Configs/NoSignalJunction.xml, Configs/ObjectCrossing.xml, Configs/RunningRedLight.xml, Configs/VehicleTurning.xml, Docs/coding_standard.md, Docs/creating_new_scenario.md, Docs/getting_started.md, ScenarioManager/atomic_scenario_behavior.py, ScenarioManager/atomic_scenario_criteria.py, ScenarioManager/carla_data_provider.py, ScenarioManager/result_writer.py, ScenarioManager/scenario_manager.py, Scenarios/basic_scenario.py, Scenarios/config_parser.py, Scenarios/control_loss.py, Scenarios/follow_leading_vehicle.py, Scenarios/no_signal_junction_crossing.py, Scenarios/object_crash_intersection.py, Scenarios/object_crash_vehicle.py, Scenarios/opposite_vehicle_taking_priority.py, Utilities/code_check_and_formatting.sh, manual_control.py, scenario_runner.py
Major rework of the scenario runner:
- Every scenario has to have a configuration provided as XML file.
Currently there is one XML file for each scenario class
Important: Scenario names need to be unique!
- The scenario runner is now responsible for spawning/destroying all actors.
- All scenarios from one config file can be executed as follows: "./scenario_runner.py --scenario group:<name_of_group>", single scenarios can be executed as in the past
- Renamed vehicle -> actor
- Refactoring of scenario_runner to use class
- Added randomization option for scenario parameters (see FollowLeadingVehicle as example)
New atomic behaviors:
- InTriggerDistanceToNextLocation
- StandStill
Generalization of scenarios:
- ControlLoss (removed region checks, derived start/end locations from init vehicle …
=> Rework of scenario manager, support for config files and generalization of scenarios

CHANGELOG.md, ScenarioManager/atomic_scenario_behavior.py
The current throttle/brake values are now maintained.
Checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/34)
=> Fixed velocity issue for Steering atomic

srunner/challenge/challenge_evaluator.py, srunner/challenge/envs/server_manager.py
Workaround to fix some issues in the server manager related to stdout.
Fixes #  
* **CARLA version:** 0.9.4-pre
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/53)
=> workaround to deal with server manager issues related to stdout blocking

Docs/agent_evaluation.md, Docs/challenge_evaluation.md, Docs/getting_started.md, README.md
Initial documentation for the challenge evaluator system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/47)
=> Challenge evaluator documentation

srunner/scenariomanager/traffic_events.py
Emergency fix of traffic events
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/61)
=> fixing traffic events

CHANGELOG.md, srunner/challenge/challenge_evaluator.py, srunner/scenariomanager/atomic_scenario_criteria.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/scenario_manager.py, srunner/scenariomanager/traffic_events.py, srunner/scenarios/challenge_basic.py, srunner/scenarios/config_parser.py, srunner/scenarios/opposite_vehicle_taking_priority.py
Add method to obtain next relevant traffic light for an actor via the CarlaDataProvider module
Checklist:
* **Python version(s):** Python 2.7, 3.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/69)
=> Access to traffic lights

CHANGELOG.md, Docs/list_of_scenarios.md, srunner/configs/ControlLoss.xml, srunner/scenariomanager/atomic_scenario_behavior.py, srunner/scenarios/control_loss.py
Generalization of Traffic Scenario 01.
Fixes #  
Added noise to steer as well as throttle of the vehicle.
* **CARLA version:** ...0.9.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/56)
=> Generalization of Traffic Scenario 01

Docs/challenge_evaluation.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/71)
=> Fix link to agent evaluation

srunner/challenge/autoagents/DummyAgent.py, srunner/challenge/challenge_evaluator.py, srunner/challenge/envs/sensor_interface.py
Adding a pseudo sensors that read the speed and all the vehicle properties.
* **Platform(s):** ubuntu 16.04
* **Python version(s):** python3.5
What you read from the vehicle physics information does not seem to change over time.
It is maybe not necessary to make it as a sensor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/75)
=>  adding the CanBus

CHANGELOG.md, Docs/challenge_evaluation.md, Docs/list_of_scenarios.md, scenario_runner.py, srunner/challenge/autoagents/HumanAgent.py, srunner/challenge/challenge_evaluator.py, srunner/challenge/envs/server_manager.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenarios/basic_scenario.py, srunner/scenarios/challenge_basic.py, srunner/scenarios/control_loss.py, srunner/scenarios/follow_leading_vehicle.py, srunner/scenarios/no_signal_junction_crossing.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/opposite_vehicle_taking_priority.py
Added a CarlaActorPool to allow creation of scenario-related actors inside a scenario, but a handover to the scenario_runner after scenario completion.
Checklist:
API change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/73)
=> Added CarlaActorPool to CarlaDataProvider

CHANGELOG.md, scenario_runner.py, srunner/challenge/challenge_evaluator.py, srunner/configs/RunningRedLight.xml, srunner/scenarios/basic_scenario.py, srunner/scenarios/control_loss.py, srunner/scenarios/opposite_vehicle_taking_priority.py, srunner/scenarios/scenario_helper.py
Checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/77)
=> Generalization of Scenario 07

srunner/challenge/challenge_evaluator.py, srunner/challenge/envs/server_manager.py
importlib.utils is not working properly in Python2, therefore changed
agent import in challenge_evaluator
Checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/79)
=> Updated challenge_evaluator to be usable with Python2

CHANGELOG.md, scenario_runner.py, srunner/challenge/challenge_evaluator.py, srunner/configs/FollowLeadingVehicle.xml, srunner/scenarios/basic_scenario.py, srunner/scenarios/challenge_basic.py, srunner/scenarios/control_loss.py, srunner/scenarios/follow_leading_vehicle.py, srunner/scenarios/no_signal_junction_crossing.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/opposite_vehicle_taking_priority.py
Checklist:
The first behavior of a scenario is now a "wait" behavior, which is resolved once the ego vehicle reached the scenario start location. The release of the "wait" behavior is based on a 2 seconds time to arrival to the defined ego_vehicle location in the XML/json
* **Python version(s):** 2.7, 3.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/84)
=> Added scenario start location + wait behavior

CHANGELOG.md, srunner/challenge/autoagents/DummyAgent.py, srunner/challenge/autoagents/autonomous_agent.py, srunner/challenge/challenge_evaluator.py, srunner/challenge/envs/scene_layout_sensors.py, srunner/challenge/envs/sensor_interface.py, srunner/scenariomanager/scenario_manager.py
Added two pseudo sensors:
scene layout reader
and object finder.
The scene layout reader returns the complete description of the scene in form of connected
waypoints.  
The object finder returns a dictionary with the position of all the objects. 
The sensors by itself are done. However the returned description of the scene needs
further testing.
* **Platform(s):** ubuntu 16.04
* **Unreal Engine version(s):** 
* **CARLA version:**  needs to link to   https://github.com/carla-simulator/carla/tree/manishthani/no_rendering_mode  branch or my test branch https://github.com/carla-simulator/carla/tree/fcodevilla/scene_layout_interface
None that I saw
--- …
=> Track 4 - Scene layout sensors

CHANGELOG.md, scenario_runner.py, srunner/scenarios/basic_scenario.py
Added method _initialize_actors to basic scenario. Which can be overridden from the child class for scenario specific actor initialisation.
_Fixes:_ 
* Spell check
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/86)
=> Custom actor initialization

CHANGELOG.md, srunner/scenarios/scenario_helper.py
Added various helper methods for generic scenario execution.
* get_waypoint_in_distance() : returns a waypoint for a given distance  from actor's position.
* generate_target_waypoint(): follow waypoints to a junction and choose path based on turn input. It returns waypoint according to turn input. 
*choose_at_junction(): This function chooses the appropriate waypoint from next_choices based on direction
*get_intersection(): Obtain a intersection point between two actor's location, return the intersection location.
* **Platform(s):**  ubuntu 18.04
* **Python version(s):**  2.7
--- …
=> Helper methods

CHANGELOG.md, srunner/scenariomanager/atomic_scenario_behavior.py
Added the following atomic behaviours
* WaypointFollower: follows auto-generated waypoints indefinitely or follows a given waypoint list
* HandBrakeVehicle: sets the handbrake value for a given actor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/89)
=> Added new atomic behaviours

scenario_runner.py, srunner/configs/VehicleTurning.xml, srunner/scenarios/basic_scenario.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/scenario_helper.py
Generalization of Traffic scenario 04:
Other actors are spawning with respect to the location of ego vehicle's location.
Code has been checked against pep8 and pylint.   
Fixes #  
* **Platform(s):** Linux
* **Python version(s):**  2.7
* Due to lane width issue in town 03
* Possible spawning issue in some locations in Town05
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/74)
=> Generalization of Traffic Scenario 04

srunner/scenariomanager/scenario_manager.py, srunner/scenarios/basic_scenario.py
Fixes a problem running sequences of scenarios. The BasicScenario musn't have static members.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/90)
=> minor fix to support sequnces of scenarios

CHANGELOG.md, srunner/scenariomanager/scenario_manager.py, srunner/scenarios/basic_scenario.py, srunner/scenarios/control_loss.py, srunner/scenarios/follow_leading_vehicle.py, srunner/scenarios/maneuver_opposite_direction.py, srunner/scenarios/no_signal_junction_crossing.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/opposite_vehicle_taking_priority.py
* Added criteria_enable flag
_Fixes #_  
* Removed redundant function copy from basic scenario
* Spell check
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/92)
=> Criteria enable flag

scenario_runner.py
ScenarioRunner automatically loads the map to start a scenario
Fixes #  
* **Platform(s):** Ubunty 16.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/94)
=> automatic map loading for all scenarios

scenario_runner.py, srunner/configs/FollowLeadingVehicle.xml, srunner/scenarios/follow_leading_vehicle.py, srunner/scenarios/signalized_junction_left_turn.py
Fixed spawning issue for TS02 for town02.
Fixes #  
Incremented z value by 1 in initialize actors method to fix the issue of unable to spawn due to collision at spawn point.
* **Platform(s):** 18.04
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/99)
=> Fix for spawning issue in Traffic Scenario 02

srunner/scenarios/basic_scenario.py
Change-Id: I95d7b1b4900536137f4363d0afb23b514f84de13
Checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/96)
=> Fixed timeout handling in BasicScenario

CHANGELOG.md, scenario_runner.py, srunner/challenge/envs/scene_layout_sensors.py, srunner/challenge/envs/sensor_interface.py, srunner/scenariomanager/atomic_scenario_behavior.py, srunner/scenariomanager/atomic_scenario_criteria.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenarios/basic_scenario.py, srunner/scenarios/follow_leading_vehicle.py, srunner/scenarios/maneuver_opposite_direction.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/other_leading_vehicle.py, srunner/scenarios/scenario_helper.py, srunner/scenarios/signalized_junction_left_turn.py, srunner/scenarios/signalized_junction_right_turn.py
WIP: universal access to the map without re-calling get_map. This change is done to avoid the overhead of re-loading the opendrive file 
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/95)
=> WIP: universal access to the map without re-calling get_map

srunner/scenariomanager/atomic_scenario_criteria.py, srunner/scenariomanager/traffic_events.py, srunner/scenarios/challenge_basic.py
Adds test to check if a vehicle is on a sidewalk and generates a TrafficEvent associated to that event
Fixes #  
* **Platform(s):** Ubunty 16.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/103)
=> Dev sidewalk test

srunner/scenariomanager/atomic_scenario_criteria.py
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/104)
=> hotfix: Fix terminate method in OnSidewalkTest criterion

srunner/configs/SignalizedJunctionLeftTurn.xml, srunner/scenarios/scenario_helper.py, srunner/scenarios/signalized_junction_left_turn.py
* Adversary vehicle triggers when ego is inside the intersection.
* fixed choose_at_junction helper function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/102)
=> Updated TS 08

srunner/configs/ObjectCrossing.xml, srunner/scenarios/object_crash_vehicle.py
* For stationary class cyclist is replaced by container
* For dynamic class cyclist is now behind a large object (vending machine)
* **Platform(s):** Linux 18.04
Spawning issue in town 03 and town 05 due to waypoints not positioned at the
centre of lanes, see:
https://github.com/carla-simulator/carla/issues/1349
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/100)
=> Updated traffic scenario 03: added static object to scenario

srunner/challenge/challenge_evaluator.py, srunner/challenge/envs/scene_layout_sensors.py
Hot fix for the change in carla repo and the adding of the carla data provider 
data provider pool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/109)
=> Development fixing data pool

CHANGELOG.md, scenario_runner.py, srunner/challenge/challenge_evaluator.py, srunner/scenarios/basic_scenario.py, srunner/scenarios/config_parser.py, srunner/scenarios/follow_leading_vehicle.py, srunner/scenarios/maneuver_opposite_direction.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/other_leading_vehicle.py
This PR updates the reference location of scenarios, that now is called trigger_point. It also fixes #106 
Fixes #106
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/108)
=> Feat trigger location scenario

srunner/scenarios/basic_scenario.py
This is required to ensure correct actor transforms for further
processing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/111)
=> HotFix: Added wait_for_tick after spawning scenario actors

srunner/scenarios/control_loss.py
*Added sequence of perturbations with some time gap.
* **Platform(s):**  Ubuntu 18.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/101)
=> Updated TS 01

srunner/configs/ObjectCrossing.xml, srunner/scenariomanager/atomic_scenario_behavior.py, srunner/scenariomanager/atomic_scenario_criteria.py, srunner/scenarios/challenge_basic.py, srunner/scenarios/object_crash_vehicle.py
- Added pedestrian to traffic scenario 03 
- Updated atomic scenario behaviors to support "WalkerControl"
- Added Town03 location
* **Platform(s):** 18.04
* **Unreal Engine version(s):** 4.2.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/113)
=> Updated TS03 to support pedestrian

CHANGELOG.md, srunner/scenariomanager/atomic_scenario_behavior.py, srunner/scenarios/scenario_helper.py
* Modified WaypointFollower to detect obstacle.
* Added atomic behaviours ActorSource and ActorSink
* Modified WaypointFollower to handle a list of vehicles simultaneously.
* Moved one-time initialization to setup() method of WaypointFollower atomic behavior.
* Check on local planner reference in update method of WaypointFollower atomic behavior.
* Added detect_lane_obstacle() helper function. 
* **Platform(s):**  Ubuntu 18.04
* Need to work on cleanup of actors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/117)
=> New and Fixed Atomic Behaviors.

CHANGELOG.md, srunner/scenariomanager/atomic_scenario_behavior.py, srunner/scenarios/maneuver_opposite_direction.py
* Modified ManeuverOppositeDirection to co-ordinate traffic flow using a blackboard queue
* Modified WaypointFollower to handle a list of vehicles simultaneously
* Added atomic behaviours ActorSource and ActorSink
* Needs clean up work to remove actor lifetime warnings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/115)
=> Traffic Flow Implementation For Traffic Scenario 06

srunner/scenarios/scenario_helper.py
For some cases the cos was getting values such as 1.000000001
breaking the math.acos function on the scenario helper.
* **Platform(s):** ubuntu
* **CARLA version:** Nighly March 25
None that I know
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/121)
=> Float imprecision bug, 

srunner/challenge/autoagents/HumanAgent.py, srunner/challenge/test_routes.py
Fix human agent, adding a sleep,
initial tests on ticking the scenarios properly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/126)
=> Fix human agent

srunner/configs/ControlLoss.xml, srunner/scenarios/control_loss.py
*Added random location for debris prop.
*Added ActorTransformSetter behavior.
* **CARLA version:** Carla overnight build.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/128)
=> Rework TS01

srunner/challenge/challenge_evaluator_routes.py
Add check for the position of the sensors used in the challenge
Fixes #  
* **CARLA version:** overnight 2019-03-28
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/124)
=> Feat check extrinsics

srunner/challenge/test_routes.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/129)
=>  adding actor registration

srunner/challenge/challenge_evaluator_routes.py, srunner/challenge/test_routes.py, srunner/challenge/utils/route_configuration_parser.py, srunner/challenge/utils/route_manipulation.py, srunner/scenariomanager/atomic_scenario_criteria.py, srunner/scenarios/master_scenario.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/signalized_junction_left_turn.py, srunner/scenarios/signalized_junction_right_turn.py, srunner/testing/test_route_spawn.py, srunner/testing/test_scenario_building.py, srunner/testing/test_spawn.py
Add tests for route spawn 
Make test routes to use challenge evaluator
Updated lane detector name
Fixed the route spawning bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/131)
=>  changing test_routes to use challenge evaluator + test + route fix

srunner/challenge/challenge_evaluator_routes.py
Update: new method to obtain the challenge phase codename
Fixes #  
* **CARLA version:** carla-overnight 2019-03-29
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/130)
=> Update: phase ID (codename) retrieval updated

srunner/scenariomanager/atomic_scenario_behavior.py, srunner/scenarios/scenario_helper.py
* WaypointFollower Atomic Behavior detect vehicles and stops accordingly.
* Fixed actor spawning error issue.
* **Platform(s):**  Ubuntu 18.04
* **Unreal Engine version(s):** UE4
* **CARLA version:** CARLA overnight build
When the actors are at the intersection, as there are number of changing lane_id's, actors find difficult to detect vehicles instantly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/134)
=> QuickFix : For WaypointFollower to detect vehicle

srunner/challenge/autoagents/DummyAgent.py, srunner/challenge/autoagents/HumanAgent.py, srunner/challenge/autoagents/Track4SampleAgent.py, srunner/challenge/challenge_evaluator_routes.py, srunner/challenge/envs/sensor_interface.py
Fix small problem with the layout_scene and the Track4 sensor
Fixes #  
* **Platform(s):** Ubunty 16.04
* **CARLA version:** overnight 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/133)
=> Fix track4

Docs/getting_started.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/141)
=> Update README prerequisites

srunner/scenarios/maneuver_opposite_direction.py
* Increased the gap between the vehicles in flow
* Decreased the flow velocity
* **CARLA version:** Latest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/142)
=> Tuned traffic scenario 06

CHANGELOG.md, srunner/challenge/autoagents/HumanAgent.py, srunner/challenge/challenge_evaluator_routes.py, srunner/challenge/run_evaluator.sh, srunner/scenarios/maneuver_opposite_direction.py
Added compatibility with python 2.7 for the challenge evaluation code
Fixes #  
* **CARLA version:** overnight 2019-04-03
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/144)
=> Fix python27

srunner/challenge/challenge_evaluator_routes.py
Added functionality to visualize scenarios within a given route (trigger points and scenario type)
Fixes #  
* **CARLA version:** overnight 2019-04-03
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/145)
=> Feat: adding visualization of scenarios on the map

srunner/configs/RunningRedLight.xml, srunner/scenariomanager/atomic_scenario_behavior.py, srunner/scenarios/config_parser.py, srunner/scenarios/control_loss.py, srunner/scenarios/maneuver_opposite_direction.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/opposite_vehicle_taking_priority.py, srunner/scenarios/scenario_helper.py
Completed rework of scenario 07 according to feedback. We did not use a stream of adversaries for now, to increase the challenge of this scenario, but we modified the behavior to ensure a collision for various driving behaviors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/107)
=> Rework of TS07

Docs/getting_started.md, srunner/scenarios/scenario_helper.py
* Changed implementation using sequentially sliced overlap detection.
* **CARLA version:** Carla overnight build of 1st April
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/143)
=> Updated detect_lane_obstacle()

srunner/challenge/challenge_evaluator_routes.py, srunner/challenge/test_challenge_route.py, srunner/challenge/utils/route_configuration_parser.py, srunner/challenge/utils/route_manipulation.py
Fix route - scenario trigger matching bug
* **Platform(s):** 
* **CARLA version:** nightly 4 of april
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/148)
=> Fix position bug

srunner/challenge/challenge_evaluator_routes.py
Terminate the scenarios on the main loop. And write at the blackboard
* **Python version(s):** 3.5  * **Unreal Engine version(s):** ...
* **CARLA version:** 9.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/149)
=>  adding scenario termination

srunner/challenge/test_challenge_route.py
Empty json added and adding blackboard to test challenge route.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/155)
=> Empty json fix

srunner/challenge/no_scenarios.json
hotfix, forgot json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/156)
=>  acidentally removed json content fix

scenario_runner.py, srunner/challenge/run_evaluator.sh, srunner/configs/MasterScenario.xml, srunner/scenariomanager/atomic_scenario_criteria.py, srunner/scenarios/background_activity.py, srunner/scenarios/master_scenario.py
Fixed issues with the sidewalk detection test and the running stop sign test.
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/158)
=> Fix: sidewalk test and stop test fixed

srunner/configs/ObjectCrossing.xml, srunner/scenarios/object_crash_vehicle.py
* start condition is independent of ego_vehicle
* actors and props are spawning from sidewalk
* **Platform(s):**  18.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/153)
=> Improvement in actor spawning for TS03

srunner/scenarios/object_crash_intersection.py
* start condition is independent of ego_vehicle
* actor will spawn from sidewalk
* **Platform(s):** Linux 18.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/154)
=> Improvement in actor spawning for TS04

srunner/challenge/challenge_evaluator_routes.py
Title says all
Checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/166)
=> Fixed loading new world after client crashed

CHANGELOG.md, srunner/challenge/challenge_evaluator_routes.py, srunner/challenge/run_evaluator.sh
Added a global wall time timeout for the CARLA challenge
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/168)
=> Feat timeout

srunner/challenge/challenge_evaluator_routes.py, srunner/challenge/run_evaluator.sh
Added repetitions to the challenge, with different weather profiles
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/169)
=> Feat repetitions

srunner/challenge/challenge_evaluator_routes.py, srunner/scenarios/background_activity.py, srunner/scenarios/control_loss.py, srunner/scenarios/follow_leading_vehicle.py, srunner/scenarios/maneuver_opposite_direction.py, srunner/scenarios/master_scenario.py, srunner/scenarios/no_signal_junction_crossing.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/opposite_vehicle_taking_priority.py, srunner/scenarios/other_leading_vehicle.py, srunner/scenarios/signalized_junction_left_turn.py, srunner/scenarios/signalized_junction_right_turn.py
Timeout added as parameter to scenarios.
* **CARLA version:** 9.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/170)
=> Timeout added as parameter to scenarios

srunner/challenge/challenge_evaluator_routes.py
Added simulation timeout based on the length of a route
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/171)
=> Feat: add simulation time timeout based on the lenght of a route

srunner/tools/scenario_helper.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/152)
=> Added null check on waypoint.next() call in helper function

srunner/challenge/autoagents/DummyAgent.py, srunner/challenge/autoagents/HumanAgent.py, srunner/challenge/autoagents/Track4SampleAgent.py, srunner/challenge/autoagents/autonomous_agent.py
Add timestamp to autonomous_agent (simulation time).
Fixes #  
* **CARLA version:** carla-overnight 2019-04-09
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/178)
=> Feat: add timestamp to autonomous_agent

.pylintrc, scenario_runner.py, srunner/challenge/challenge_evaluator_routes.py, srunner/challenge/test_routes.py, srunner/challenge/utils/route_configuration_parser.py, srunner/challenge/utils/route_manipulation.py, srunner/scenariomanager/atomic_scenario_behavior.py, srunner/scenariomanager/atomic_scenario_criteria.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/scenario_manager.py, srunner/scenariomanager/traffic_events.py, srunner/scenarios/background_activity.py, srunner/scenarios/basic_scenario.py, srunner/scenarios/control_loss.py, srunner/scenarios/follow_leading_vehicle.py, srunner/scenarios/maneuver_opposite_direction.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/opposite_vehicle_taking_priority.py, srunner/scenarios/other_leading_vehicle.py, srunner/scenarios/signalized_junction_left_turn.py, srunner/scenarios/signalized_junction_right_turn.py, srunner/tools/config_parser.py, srunner/tools/scenario_helper.py
Fixed all issues in
- srunner/scenariomanager
- srunner/scenarios
- srunner/tools
Started with
- srunner/challenge
Change-Id: I066f900f73ec802465481d2bd7afc1fca1eddea3
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/179)
=> Fixing pylint issues

srunner/challenge/challenge_evaluator_routes.py
Lidar range is in centimeters. Therefore 2m is not very helpful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/182)
=> Set range of Lidar to 50m

srunner/challenge/envs/scene_layout_sensors.py, srunner/challenge/envs/sensor_interface.py
Hotfix: add stop method to all pseudo-sensors
Fixes #  
* **CARLA version:** overnight 2019-04-09
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/183)
=> Hotfix: add stop method to all pseudo-sensors

srunner/challenge/envs/sensor_interface.py
Hotfix: update sensor_interface to use float64 for GPS pseudo-sensor
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/185)
=> Hotfix gps sensor float64

CHANGELOG.md, srunner/challenge/challenge_evaluator_routes.py
Feat: add logging functionalities to challenge_evaluator_routes.py
Fixes #  
* **Platform(s):** Ubunty 16.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/186)
=> Feat logging challenge

srunner/challenge/autoagents/HumanAgent.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/object_crash_vehicle.py
*Added break condition after 10 attempts of spawning
*On breaking intialize status is changed to False
* **Platform(s):** Linux 18.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/188)
=> Handeling infinite loop 

srunner/scenarios/object_crash_intersection.py
Fixes #  
* Added null check
* Raising runtime error if waypoint cannot be generated
Note: This PR is rebased on top of PR 188
* **Unreal Engine version(s):** 4.12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/190)
=> Added null check to get_opponent_transform

srunner/challenge/autoagents/Track4SampleAgent.py, srunner/challenge/challenge_evaluator_routes.py, srunner/challenge/envs/scene_layout_sensors.py
Exceptions should now be caught and should no longer lead to a complete
crash of the challenge execution.
* **CARLA version:** Latest master
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/189)
=> Made challenge_evaluator more robust + Fixed sensor cleanup + Fix Track4

srunner/challenge/challenge_evaluator_routes.py
We delete the agent and the sensors  before the scenarios.
* **CARLA version:** latest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/192)
=>  we remove the agent and sensors first

srunner/challenge/autoagents/HumanAgent.py
infinite loop on human agent fix
* **CARLA version:**  latest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/197)
=>  human agent infinite first loop

srunner/challenge/challenge_evaluator_routes.py
Feat: add follow hero in CARLA server when debug==1
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/198)
=> Feat follow hero

srunner/challenge/challenge_evaluator_routes.py, srunner/scenariomanager/carla_data_provider.py
Avoid to spawn background actors close to the hero actor to avoid premature collision
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/199)
=> Avoid spawn close hero

srunner/challenge/autoagents/ros_agent.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/203)
=> Update ros-agent after bridge change

srunner/scenarios/signalized_junction_left_turn.py
* Modified TS 08 to co-ordinate traffic flow using a blackboard queue
* **Unreal Engine version(s): UE4
* **CARLA version:** CARLA overnight build
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/135)
=> Traffic Flow Implementation For TS08

srunner/challenge/challenge_evaluator_routes.py, srunner/challenge/run_evaluator.sh
Hotfix: the number of repetitions is set according to the phase and the debug flag
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/206)
=> Hotfix repetitions

srunner/challenge/challenge_evaluator_routes.py
problem , still missing args on repetitions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/207)
=>  repetitions hotfix

srunner/scenarios/object_crash_vehicle.py
Remove physics from the carla cola machine and place it closer to the ground
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/208)
=>  non physical carla cola machine

srunner/scenariomanager/atomic_scenario_behavior.py
reseting traffic jam checker timer on traffic lights
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/211)
=>  Background: reseting on traffic light

srunner/scenarios/object_crash_intersection.py
Use distance along route to activate scenario 04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/214)
=>  calculate the distance along route TS4

srunner/challenge/challenge_evaluator_routes.py
Bug that made the pseudo sensors to crash because the vehicle was eliminated before the sensors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/218)
=> Bug: Changing the sensor order.

srunner/challenge/challenge_evaluator_routes.py
Update: seconds given per mile is now set to 0.4
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/219)
=> Update: seconds given per mile is now set to 0.4

srunner/challenge/test_challenge_route.py, srunner/challenge/test_routes.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/other_leading_vehicle.py
Added avoid collision flag, and adversary vehicle now doesn't crash with any other vehicle. 
Fixes #  
* **Platform(s):** 18.04
* **Python version(s):**2.7
* **Unreal Engine version(s):**4.21
* **CARLA version:**0.9.5
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/164)
=> Fix for crash in Traffic Scenario 05

srunner/challenge/challenge_evaluator_routes.py
Feat: update the timing of traffic light to make towns more dynamic
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/223)
=> Feat: update the timing of traffic light to make towns more dynamic

srunner/challenge/challenge_evaluator_routes.py
Show only the interesting parts of the py_trees debug info when running with --debug=1
* **CARLA version:** From Friday
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/221)
=> Enhanced debugging

srunner/challenge/challenge_evaluator_routes.py, srunner/challenge/utils/route_manipulation.py
Adding color to the drawed waypoints to correspond to the RoadOptions. 
* **CARLA version:** Latest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/224)
=> Adding colors to lanechanges

srunner/scenarios/object_crash_vehicle.py
Adding InTriggerDistanceToLocationAlongRoute behaviour to the tree
* removed timeout from the tree
* added names to the leaf nodes for better log entry
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/226)
=> Adding InTriggerDistanceToLocationAlongRoute behaviour to the tree in TS03

srunner/challenge/autoagents/autonomous_agent.py, srunner/challenge/utils/route_manipulation.py
For track2 and track 1 we downsample the distance between waypoints to 32 meters.
* **Unreal Engine version(s):** 
* **CARLA version:** Latest
Is it necessary to downsample for the other tracks ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/228)
=>  making a downsampling to around 32 meters distance for Tracks 1 and 2

Docs/ros_agent.md, srunner/challenge/autoagents/ros_agent.py
This caused issues after the first execution
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/225)
=> ros-agent: remove startup of roscore

srunner/scenariomanager/atomic_scenario_criteria.py, srunner/scenarios/master_scenario.py
Fix: criteria can know deal with cycles
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/229)
=> Fix: criteria can know deal with cycles

srunner/challenge/challenge_evaluator_routes.py, srunner/scenariomanager/atomic_scenario_criteria.py
* fixed bug in route deviation criterion
* fixed bug in main challenge_evaluator_routes script: tip() not defined
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/232)
=> Hotfix: route deviation criterion and misc

srunner/scenariomanager/atomic_scenario_criteria.py, srunner/scenarios/control_loss.py
Fix: sidewalk invasion and increased noise for TS01
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/233)
=> Fix: sidewalk invasion and increased noise for TS01

srunner/challenge/autoagents/autonomous_agent.py
Was crashing track 2 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/235)
=>  downsampling bug fix

srunner/challenge/autoagents/ros_agent.py, srunner/challenge/envs/sensor_interface.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/234)
=> Add opendrive to HDMaps sensor-data

srunner/challenge/challenge_evaluator_routes.py
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/236)
=> Fix: bug in scores fixed

srunner/challenge/challenge_evaluator_routes.py
The idea is to add the error message when there is a crash to the result.json file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/237)
=> Add error messages to the user

srunner/challenge/autoagents/ros_agent.py
Eliminates SyntaxWarnings  created by ros_agent.py by explicitly creating publishers with queue_size argument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/240)
=> Eliminate ROS warnings by setting queue_size

srunner/challenge/challenge_evaluator_routes.py, srunner/scenariomanager/atomic_scenario_criteria.py
Update: route completio criterion updated
Fixes #  
* **CARLA version:** overnight 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/243)
=> Feature metrics update

srunner/scenariomanager/atomic_scenario_criteria.py
There were bugs that the vehicle was going off route even when perfectly on route.
Example:
Second route from Town08, just in the beginning 
I dont know but it is possible that off route is not well detected on curves ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/245)
=>  increasing the window size

srunner/challenge/autoagents/ros_agent.py
Title says all
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/248)
=> Added timestamp and speed to ROS agent odometry

srunner/scenariomanager/atomic_scenario_criteria.py, srunner/scenariomanager/carla_data_provider.py
Fix: Pedestrian is now mortal and pedestrian impacts are not double counted
Fixes #  
* **CARLA version:** overnight May-16-2019
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/252)
=> Fix pedestrian

srunner/challenge/challenge_evaluator_routes.py
modified script to run town09
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/253)
=> Test town9

srunner/challenge/autoagents/ros_agent.py
So far the RosAgent did NOT use the stepping mode. Now it is possible to use it.
* **Python version(s):** 2.6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/254)
=> Enable stepping mode when using the RosAgent

srunner/scenariomanager/atomic_scenario_criteria.py
Fix: red lights logic
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/255)
=> Fix trafficlights

srunner/challenge/challenge_evaluator_routes.py
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/258)
=> Update: json file metadata

srunner/challenge/Dockerfile.master
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/259)
=> Fix: dockerfile update to copy the latest carla.egg

srunner/challenge/challenge_evaluator_routes.py
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/262)
=> increasing timeouts

srunner/challenge/autoagents/autonomous_agent.py, srunner/challenge/challenge_evaluator_routes.py
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/264)
=> Fix carla freeze

srunner/challenge/challenge_evaluator_routes.py
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/265)
=> Updated spectator and tree debug off due to ascii problem

srunner/challenge/challenge_evaluator_routes.py
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/266)
=> Fix: protecting code of cleanup/del operator

srunner/challenge/autoagents/autonomous_agent.py, srunner/scenariomanager/timer.py
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/267)
=> Fix walltime

srunner/challenge/challenge_evaluator_routes.py
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/268)
=> metadata activated for debug phase

srunner/scenariomanager/atomic_scenario_criteria.py
After increasing the radius for InRoute, also the radius for the
RouteCompletionTest had to be increased
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/269)
=> Increased radius for RouteCompletionTest

srunner/challenge/challenge_evaluator_routes.py
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/271)
=> FIx: atexit

srunner/challenge/challenge_evaluator_routes.py
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/272)
=> adding a sleep after a reconnection attempt

srunner/challenge/envs/sensor_interface.py
Due to the requirements of our control, we need more information about the car's physical model states. Therefore, some additional information form the CANBUS sensor is needed.  This is why, the following changes were made:
- We need the lateral speed on the vehicle, so the function "_get_lateral_speed" was added, it is based in "_get_forward_speed" and the transformation matrix was performed according to [this reference](https://i0.wp.com/slideplayer.com/4241728/14/images/34/Roll+Pitch+Yaw+The+rotation+matrix+for+the+following+operations%3A+X+Y+Z.jpg). Additionally, we noticed that the pitch's sinus on the z axis's orientation variable, in "_get_forward_speed",  should be negative.
-  Since the vehicle's orientation and the car's bounding box are necessary to compute the controller, the …
=> Additional information CANBUS added: lateral speed function, vehicle dimensions and transform

traffic_manager/source/include/ActorLocalizationCallable.hpp, traffic_manager/source/include/SharedData.hpp, traffic_manager/source/include/SimpleWaypoint.hpp, traffic_manager/source/src/ActorLocalizationCallable.cpp, traffic_manager/source/src/ActorStateCallable.cpp, traffic_manager/source/src/InMemoryMap.cpp, traffic_manager/source/src/SimpleWaypoint.cpp, traffic_manager/source/test/main.cpp
Completed Localisation stage class
Fixes #  
* **CARLA version:** ...0.9.4
Need improvement in base classes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/281)
=> Traffic Manager Update on base classes

srunner/challenge/autoagents/ros_agent.py, srunner/challenge/challenge_evaluator_routes.py
Improved cleanup of ros_agent in the faith of improving robustness
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/288)
=> Improved robustness of ros_agent

srunner/challenge/challenge_evaluator_routes.py, srunner/challenge/envs/sensor_interface.py, srunner/scenariomanager/atomic_scenario_criteria.py
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/289)
=> Fix sensors timeout

srunner/challenge/challenge_evaluator_routes.py
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/292)
=> UI fix scores

traffic_manager/source/include/ActorLocalizationCallable.hpp, traffic_manager/source/include/BatchControlCallable.hpp, traffic_manager/source/src/ActorLocalizationCallable.cpp, traffic_manager/source/src/ActorPIDCallable.cpp, traffic_manager/source/src/BatchControlCallable.cpp, traffic_manager/source/test/main.cpp
Removed bug in Test method and improved waypoint buffer update method.
Fixes #  
* **CARLA version:** ...0.9.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/293)
=> Modified Stage classes and test function

traffic_manager/source/include/BatchControlCallable.hpp, traffic_manager/source/include/FeederCallable.hpp, traffic_manager/source/src/BatchControlCallable.cpp, traffic_manager/source/src/FeederCallable.cpp, traffic_manager/source/test/main.cpp
Complete implementation of Batch control stage. Added adaptive compute scaling.
Fixes #  
* **CARLA version:** ...0.9.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/297)
=> Feeder auto-scaling, Batch Stage complete

traffic_manager/source/include/SharedData.hpp, traffic_manager/source/src/ActorLocalizationCallable.cpp, traffic_manager/source/src/InMemoryMap.cpp, traffic_manager/source/test/main.cpp
Fixed memory access bugs in ActorLocalizationCallable
Removed zero length segments from topology
Fixes #  
* **CARLA version:** ...0.9.5+
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/300)
=> Localization fixed

traffic_manager/source/include/ActorPIDCallable.hpp, traffic_manager/source/include/CollisionCallable.hpp, traffic_manager/source/include/Rectangle.hpp, traffic_manager/source/src/ActorPIDCallable.cpp, traffic_manager/source/src/BatchControlCallable.cpp, traffic_manager/source/src/CollisionCallable.cpp, traffic_manager/source/src/FeederCallable.cpp, traffic_manager/source/src/Rectangle.cpp, traffic_manager/source/test/main.cpp
Implemented collision avoidance stage by checking possible intersection between 2 vehicle's rectangluar boundary boxes calculated from Rectangle class.
Fixes #  
* **CARLA version:** ...0.9.5+
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/309)
=> Implementation of Collision Avoidance Stage

traffic_manager/source/include/TrafficLightStateCallable.hpp, traffic_manager/source/src/TrafficLightStateCallable.cpp, traffic_manager/source/test/main.cpp
Implemented TrafficLightState to control the vehicles according to traffic lights.
Fixes #  
* **Platform(s):** ...Ubuntu 18.04
* **CARLA version:** ...0.9.5+
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/310)
=> Implementation of TrafficLightState Stage

CHANGELOG.md, srunner/scenariomanager/atomic_scenario_behavior.py
Use initialise() method instead of setup().
Fixes #302
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/313)
=> Fixed initialization of WaypointFollower behavior

Docs/openscenario_support.md, srunner/scenarios/open_scenario.py, srunner/tools/openscenario_parser.py
Added initial support for custom maneuver commands for OpenScenario. Added support for command 'Idle' and extended maneuver handling to consider also ego vehicles for maneuver actions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/317)
=> Added initial support for custom maneuver commands for OpenScenario

CHANGELOG.md, Docs/agent_evaluation.md, Docs/challenge_evaluation.md, Docs/getting_started.md, srunner/configs/CyclistCrossing.xosc, srunner/configs/FollowLeadingVehicle.xosc
The getting_started documentation contained a non-completed PYTHONPATH.
Resolves #311 
Fixes #319 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/318)
=> Fixed PythonPath in documentation

CHANGELOG.md, Docs/challenge_evaluation.md, Docs/getting_started.md, README.md, manual_control.py, scenario_runner.py, srunner/challenge/challenge_evaluator_routes.py, srunner/challenge/envs/scene_layout_sensors.py, srunner/challenge/envs/sensor_interface.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/timer.py, srunner/scenarios/basic_scenario.py
Update to CARLA 0.9.6
Fixes #320
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/321)
=> Update to CARLA 0.9.6

.gitignore, requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/322)
=> Added requirements file

traffic_manager/source/include/SimpleWaypoint.hpp, traffic_manager/source/include/TrafficLightStateCallable.hpp, traffic_manager/source/src/CollisionCallable.cpp, traffic_manager/source/src/SimpleWaypoint.cpp, traffic_manager/source/src/TrafficLightStateCallable.cpp, traffic_manager/source/test/main.cpp
Added check Junction method for waypoints.
Set lower limit for bounding box.
* **CARLA version:** ...0.9.5+
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/326)
=> Resolved false traffic light detections

CHANGELOG.md, scenario_runner.py, srunner/configs/FollowLeadingVehicle.xosc, srunner/scenariomanager/timer.py, srunner/tools/openscenario_parser.py
Added full support for SimulationTime condition for OpenScenario
Checklist:
Fixes #327 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/330)
=> Added full support for SimulationTime condition for OpenScenario

traffic_manager/source/src/CollisionCallable.cpp
Implemented better Collision Detection method using Vehicle's heading vector and relative position vector to other vehicles.
* **CARLA version:** ...0.9.6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/331)
=> Implemented better Collision Detection

CHANGELOG.md, srunner/configs/PedestrianCrossingfront.xosc, srunner/scenariomanager/atomic_scenario_behavior.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenarios/object_crash_vehicle.py, srunner/tools/openscenario_parser.py
Added initial support for pedestrians in OpenSCENARIO
Pedestrians can now be used in OpenSCENARIO scenarios.
Checklist:
Addresses #329 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/333)
=> Added initial support for pedestrians in OpenSCENARIO

scenario_runner.py
The method load_world was renamed to load_and_wait_for_world to reflect
that the world is not only loaded upon request, but that also the
scenario_runner waits for the world to be ready, including the
availability of all ego vehicles, if this is requested via --waitForEgo.
Checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/336)
=> Rework load_world method in scenario_runner

srunner/tools/openscenario_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/337)
=> Added warning if start position for an actor is missing for OpenSCENARIO

srunner/challenge/autoagents/ros_agent.py
ros bridge for 0.9.6 changes datatype with https://github.com/carla-simulator/ros-bridge/pull/170
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/340)
=> ROS agent: use /carla/world_info instead of /carla/map

srunner/challenge/challenge_evaluator_routes.py
Fixes not moving ego vehicle in #323
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/345)
=> Fixed missing rolename for ego vehicle in challenge_evaluator_routes

scenario_runner.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/353)
=> Fix waiting for ego vehicle

scenario_runner.py, srunner/scenarios/open_scenario.py, srunner/tools/config_parser.py
This change is mainly a cleanup of scenario_runner codebase to have cleaner python imports and less redundant code.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/352)
=> Cleanup scenario runner

traffic_manager/source/include/CollisionCallable.h, traffic_manager/source/include/CreateGrid.hpp, traffic_manager/source/include/SharedData.h, traffic_manager/source/src/CollisionCallable.cpp, traffic_manager/source/src/CreateGrid.cpp
Implemented CreateGrid class for Grid based search for localization.
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/359)
=> implemented Grid based search for localization

traffic_manager/source/include/InMemoryMap.h, traffic_manager/source/include/SimpleWaypoint.h, traffic_manager/source/src/InMemoryMap.cpp, traffic_manager/source/src/SimpleWaypoint.cpp, traffic_manager/source/test/main.cpp
Implemented methods to find possible lane change and made corresponding linkages.
* **Platform(s):**...18.04
* **CARLA version:** ...0.9.6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/361)
=> Implemented FindAndLinkLaneChange method in InMemoryMap class

Docs/getting_started.md, Docs/openscenario_support.md, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/362)
=> Added brief roadmap to OpenSCENARIO documentation

.pylintrc, .travis.yml, CHANGELOG.md, Docs/getting_started.md, scenario_runner.py, srunner/challenge/autoagents/agent_wrapper.py, srunner/challenge/autoagents/autonomous_agent.py, srunner/challenge/autoagents/dummy_agent.py, srunner/challenge/autoagents/human_agent.py, srunner/challenge/autoagents/npc_agent.py, srunner/challenge/autoagents/ros_agent.py, srunner/challenge/autoagents/track_4_sample_agent.py, srunner/scenarioconfigs/route_scenario_configuration.py, srunner/scenarioconfigs/scenario_configuration.py, srunner/scenariomanager/scenario_manager.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/other_leading_vehicle.py, srunner/scenarios/route_scenario.py, srunner/scenarios/signalized_junction_left_turn.py, srunner/utilities/code_check_and_formatting.sh
This commit adds the option to use autonomous agents (in
srunner/challenge/autoagents) with the ScenarioRunner. At the moment
this is only possible for route-based scenarios. Agents are executed
automatically in synchronous mode.
Other changes:
- Cleanup of all agent examples according to pylint
- Added AgentWrapper class to control an agent within the
ScenarioManager
- Added signal handler inside ScenarioManager to terminate the scenario
execution properly
- Updated Travis CI to also check srunner/challenge/autoagents
Checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/s …
=> Added option to use autonomous agents with ScenarioRunner

scenario_runner.py, srunner/challenge/autoagents/agent_wrapper.py, srunner/scenariomanager/result_writer.py, srunner/scenariomanager/scenario_manager.py, srunner/scenariomanager/scenarioatomics/atomic_criteria.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/368)
=> More updates

CHANGELOG.md, scenario_runner.py, srunner/scenariomanager/scenario_manager.py, srunner/scenariomanager/scenarioatomics/atomic_criteria.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/370)
=> Cleaned Scenario class in the ScenarioManager module

srunner/scenariomanager/carla_data_provider.py
Fixes the cleanup method of CarlaDataProvider
Checklist:
Fixes #371 
* **Python version(s):** 2.7, 3.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/372)
=> Fixed cleanup of CarlaDataProvider

.gitignore, .travis.yml, CHANGELOG.md, scenario_runner.py, srunner/challenge/autoagents/npc_agent.py, srunner/challenge/challenge_statistics_manager.py, srunner/scenarioconfigs/route_scenario_configuration.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/scenario_manager.py, srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/scenarios/route_scenario.py, srunner/tools/route_parser.py, srunner/utilities/code_check_and_formatting.sh
- Added possibility to change weather conditions for repetitions
- Added option to check for time budget
- Added default routes for each challenge track
- Added data recording
- Added penalty computation
- Added challenge statistics
All can be activated/used via the challenge commandline option
Others:
- Fixed result score for OnSidewalkTest and WrongLaneTest
Change-Id: I06717943444a21570b9a519bb16a4890e1dce212
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/375)
=> Added additional challenge features to ScenarioRunner

CHANGELOG.md, scenario_runner.py, srunner/examples/ChangeLane.xml, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenarios/change_lane.py, srunner/tools/scenario_helper.py
Added lane change behavior atomic and sample scenario
Checklist:
=> Added lane change behavior atomic and sample scenario

CHANGELOG.md, Docs/openscenario_support.md, srunner/examples/CyclistCrossing.xosc, srunner/examples/FollowLeadingVehicle.xosc, srunner/examples/PedestrianCrossingfront.xosc, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenariomanager/scenario_manager.py, srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py, srunner/scenarios/open_scenario.py, srunner/tools/openscenario_parser.py
All sequences of actions now occur in parallel
ConditionGroups allow for multiple conditions to be evaluated in parallel for logical ORs
Fixes #365 Improve logical compliance with OpenSCENARIO intent
This has not yet been tested
This could change the behaviour of existing scenarios including the order of events and triggering of conditions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/366)
=> Openscenario logic

srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py, srunner/tools/openscenario_parser.py
Less_than is no longer the only allowed rule for distance and time conditions
Less_than remains the default to support existing usage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/381)
=> Add support for all three OpenScenario logical operators

CHANGELOG.md, Docs/openscenario_support.md, scenario_runner.py, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenarioconfigs/scenario_configuration.py
Using the RoadCondition action, the road friction can be adjusted.
Checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/389)
=> Added RoadCondition support for OpenSCENARIO

CHANGELOG.md, Docs/openscenario_support.md, srunner/examples/CyclistCrossing.xosc, srunner/examples/FollowLeadingVehicle.xosc, srunner/examples/LaneChangeSimple.xosc, srunner/examples/PedestrianCrossingfront.xosc, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py, srunner/scenarios/open_scenario.py, srunner/tools/openscenario_parser.py
* Fixed usage of radians instead of degrees
* Allowed user defined act names besides 'Behavior'
* Fixed timing bug in AfterTerminationCondition
* Removed redundant rolename property
Checklist:
* **Platform(s):**  Ubuntu 16
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/390)
=> Several small fixes for the OpenSCENARIO support

srunner/scenarioconfigs/openscenario_configuration.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/394)
=> Fixed issue with empty global parameters for OpenSCENARIO

CHANGELOG.md, scenario_runner.py, srunner/examples/CutIn.xml, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenarios/cut_in.py
* Fixed ActorTransformSetter behavior
* Extended WaypointFollower behavior to allow use of current speed
* Added AccelerateToCatchUp atomic behavior
* Added CutIn example scenario
Checklist:
* **Platform(s):**  Ubuntu 16.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/395)
=> Added CutIn example scenario

srunner/tools/openscenario_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/397)
=> Fixed use of relative positions in OpenSCENARIO

srunner/scenariomanager/result_writer.py, srunner/tools/openscenario_parser.py, srunner/tools/route_parser.py, srunner/tools/scenario_helper.py
Checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/401)
=> Cleaned imports and fixed junit result writer

CHANGELOG.md, scenario_runner.py, srunner/examples/FollowLeadingVehicle.xosc, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenarioconfigs/scenario_configuration.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenarios/basic_scenario.py
* Allow vehicle colour configuration via properties
* Use a random vehicle model if the provided vehicle name isn't a valid… …
* Use vehicle categories for more appropriate random vehicles …
Checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/403)
=> Extended the support for vehicle attributes for OpenSCENARIO

CHANGELOG.md, scenario_runner.py, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py, srunner/tools/openscenario_parser.py
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/406)
=> Openscenario parser extensions

CHANGELOG.md, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/tools/openscenario_parser.py
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/411)
=> Velocity extensions

Docs/CHANGELOG.md, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenarioconfigs/scenario_configuration.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenarios/open_scenario.py, srunner/tools/openscenario_parser.py
- openscenario_configuration.py with get_actor_speed()
- scenario_configuration.py with init speed value
- atomic_behaviors.py with new atomic behavior SetOSCInitSpeed and
blackboard variable to switch off the init speed atomic
- open_scenario.py with _create_init_behavior(),
added to beginning of parallel behavior tree
- carla_data_provider with actor.id
- added new implementation to CHANGELOG
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/415)
=> init_speed

srunner/scenariomanager/scenarioatomics/atomic_behaviors.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/417)
=> Fixed AtomicBehavior initialise for None actors

.pylintrc, Docs/CHANGELOG.md, scenario_runner.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenarios/follow_leading_vehicle.py, srunner/scenarios/no_signal_junction_crossing.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/route_scenario.py, srunner/scenarios/signalized_junction_left_turn.py, srunner/scenarios/signalized_junction_right_turn.py, srunner/tools/route_parser.py
- Cleanup of exception handling
- Fixed #427
- Fixed #426 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/425)
=> WIP: Cleanup of exception handling

CARLADemo.xosc, Docs/CHANGELOG.md, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/tools/openscenario_parser.py
- Extended WaypointFollower atomic to handle pedestrians
- Changed the WaypointFollower interface, to allow routes (plans) that
use carla.Location and not carla.Waypoints.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/444)
=> OpenSCENARIO: Added support for route actions for pedestrians

Docs/CHANGELOG.md, srunner/scenariomanager/scenarioatomics/atomic_criteria.py
Revised 2 atomic criterias:
**RunningStopTest:**
Fixed a bug causing this event to trigger when lane changing near a stop signal. 
1. A new condition has been added that checks if the vehicle itself is inside the STOP signal
**RunningRedLightTest:**
Fixed a bug resulting in this event occasionally not triggering when a vehicle run a red light.
1. The waypoints that defined the crossing line have been moved outside the junction, as at intersections, multiple roads can be close by.
2. Modified the algorithm to avoid repeated calculus. Removed "area" variable from traffic lights
* **CARLA version:** 0.9.7
None?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Fixed bugs with RunningRedLightTest an RunningStopTest

scenario_runner.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/451)
=> Add return value

Docs/CHANGELOG.md, srunner/scenarios/open_scenario.py
Reworked OSC ConditionGroups to be parallel composites
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/452)
=> Reworked OSC ConditionGroups to be parallel composites

scenario_runner.py
The scenario runner cleanup () method removed the ego vehicle, although it was managed externally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/454)
=> Rework argument handling to fix cleanup in case of waitForEgo

.gitignore, scenario_runner.py
Fixed issue #462
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/463)
=> Fixed usage of --configFile parameter

Docs/CHANGELOG.md, Docs/openscenario_support.md, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/tools/openscenario_parser.py
Fixes #457
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/458)
=> Added initial support for OSCUserDefinedActions with script exec

Docs/CHANGELOG.md, scenario_runner.py, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenarioconfigs/scenario_configuration.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenarios/basic_scenario.py
The BasicScenario actor initialization now uses batch mode
initialization.
CarlaActorPool:
- Added _blueprint_library member to buffer the CARLA blueprint library
and avoid world access for every blueprint
- Added create_blueprint() to eliminate code dublication
- Added handle_actor_batch() to eliminate code dublication
- Added setup_actors() new function to spawn actors in batch mode
- Added request_new_actors() new public function to use new batch mode
(used by BasicScenario class)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/467)
=> Improved loading speed of scenarios

srunner/scenariomanager/carla_data_provider.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/468)
=> Removed exception for vehicle spawning to not break route scenarios

Docs/CHANGELOG.md, README.md, scenario_runner.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/470)
=> Release v0.9.7

Docs/CHANGELOG.md, srunner/scenariomanager/carla_data_provider.py
Fixed #472
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/473)
=> Fixed spawning issue of pedestrians in OpenSCENARIO

Docs/CHANGELOG.md, srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/tools/openscenario_parser.py
Fixed #374
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/476)
=> Fixed criteria usage with multiple ego vehicles in OpenSCENARIO

Docs/CHANGELOG.md, scenario_runner.py, srunner/examples/ChangeLane.xml, srunner/examples/CutIn.xml, srunner/examples/CyclistCrossing.xosc, srunner/examples/FollowLeadingVehicle.xml, srunner/examples/FollowLeadingVehicle.xosc, srunner/examples/LaneChangeSimple.xosc, srunner/examples/PedestrianCrossingfront.xosc, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenarioconfigs/scenario_configuration.py, srunner/tools/scenario_config_parser.py
- Adapted to API change (cloudyness -> cloudiness)
- Updated OpenSCENARIO weather parser
Fixes #471, #445
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/474)
=> Fixed weather with CARLA 0.9.7.x

srunner/examples/FollowLeadingVehicle.xosc, srunner/scenarioconfigs/openscenario_configuration.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/498)
=> Hotfix for usage with OpenSCENARIO 1.0

Docs/CHANGELOG.md, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py
Fixes #502 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/504)
=> Fixed WaypointFollower atomic when creating additional LocalPlanners on-the-fly

Docs/CHANGELOG.md, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenarios/open_scenario.py
Enabled use of scenarios with no actors based on OpenSCENARIO
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/512)
=> Enabled use of scenarios with no actors based on OpenSCENARIO

Docs/CHANGELOG.md, scenario_runner.py, srunner/autoagents/agent_wrapper.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/scenario_manager.py, srunner/scenarios/basic_scenario.py, srunner/scenarios/route_scenario.py
Removed perform_carla_tick, as it was a workaround that it isn't needed anymore.
Should this be put in the CHANGELOG?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/513)
=> Removed perform_carla_tick

README.md
Added link to version 0.9.9 at README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/518)
=> Updated README with 0.9.9 verison

Docs/CHANGELOG.md, srunner/scenarioconfigs/openscenario_configuration.py
Fixes #507
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/519)
=> Fixed initial speed settings for vehicles in OpenSCENARIO

Docs/CHANGELOG.md, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py
Added initial speed support for pedestrians in OSC
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/521)
=> Added initial speed support for pedestrians in OSC

.travis.yml, Docs/getting_started.md, requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/529)
=> Updated installation requirements and README

Docs/extra.css, Docs/openscenario_support.md, mkdocs.yml
- Format for the tables in OpenScenario support. 
* **Platform(s):** Ubuntu 18.04.4
* **Python version(s):** 3.6.9 and 2.7.17
- Check that html symbols are properly visualized in RTD.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/546)
=> sergi-e/tables-ossupport

Docs/CHANGELOG.md, srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py, srunner/tools/openscenario_parser.py
Fixed support for OSC's SpeedCondition
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/549)
=> Fixed support for OSC's SpeedCondition

Docs/CHANGELOG.md, srunner/tools/openscenario_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/550)
=> Fixed use of py_trees inverter in OSC parser

Docs/CHANGELOG.md, Docs/openscenario_support.md, srunner/scenarioconfigs/openscenario_configuration.py, srunner/tools/openscenario_parser.py
This enables usage of (local) parameters for all elements and
subelements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/552)
=> Reworked parameter handling in OSC to support local parameters

Docs/CHANGELOG.md, scenario_runner.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/561)
=> Do not register SIGHUP signal in windows

Docs/CHANGELOG.md, srunner/scenariomanager/actorcontrols/simple_vehicle_control.py
Added an additional OSC controller that uses linear and angular velocities to control an actor.
Also added support for github super-linter to improve code quality.
* **Platform(s):**  Ubuntu 16
* **CARLA version:** 0.9.9 / 0.9.9.4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/573)
=>  Added simple velocity controller for OSC entities

srunner/tools/openscenario_parser.py
Just a small hotfix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/579)
=> Fixed OSC CollisionCondition if not entities/types are provided

Docs/CHANGELOG.md, scenario_runner.py, srunner/scenariomanager/scenario_manager.py
HotFix for sync mode in OSC
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/583)
=> Added possibility to use synchronous execution mode with OSC

Docs/CHANGELOG.md, Jenkinsfile
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/587)
=> Label changes

Docs/CHANGELOG.md, Docs/openscenario_support.md, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py, srunner/tools/openscenario_parser.py
- Added support for **OSC's TrafficSignalCondition**.
- Changed **TrafficLightStateSetter** atomic behavior input to match the other atomics:
- ID (int) -> actor (carla.Actor)
- state (string) -> state (carla.TrafficLightState)
- **TrafficSignalStateAction** has been modified to accommodate the TrafficLightStateSetter changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/586)
=> Added support for OSC's TrafficSignalCondition.

srunner/scenarios/basic_scenario.py
Fixes #593
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/594)
=> Fixed cleanup of controllers in Scenario class

srunner/scenariomanager/scenarioatomics/atomic_criteria.py
Changed one parameter at RunningRedLightTest, as a traffic light at town02 wasn't being detected
* **CARLA version:** current master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/604)
=> Changed one parameter

Docs/CHANGELOG.md, srunner/scenariomanager/scenarioatomics/atomic_criteria.py
Updated leaderboard branch to current SR master
* **CARLA version:** current master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/606)
=> Update leaderboard branch

Docs/CHANGELOG.md, srunner/scenariomanager/actorcontrols/simple_vehicle_control.py
- Added support for an OpenCV camera display to visualize the current scenario
without the need to use manual_control.py
- Added support to respect obstacles in the forward facing region of the controlled
actor by using CARLA's obstacle detection sensor
Checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/609)
=> Extended OSC SimpleVehicleControl

Docs/CHANGELOG.md, srunner/scenariomanager/actorcontrols/npc_vehicle_control.py, srunner/scenariomanager/carla_data_provider.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/613)
=> Some small fixes

.travis.yml, Docs/CHANGELOG.md, requirements.txt, srunner/examples/CatalogExample.xosc, srunner/examples/catalogs/ControllerCatalog.xosc, srunner/scenarios/open_scenario.py, srunner/tools/openscenario_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/612)
=> Fix parsing of properties in ControllerCatalogs

Docs/CHANGELOG.md, srunner/tools/openscenario_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/614)
=> Support Routes from Catalogs

Docs/CHANGELOG.md, srunner/tools/openscenario_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/615)
=> Support OpenSCENARIO parameters also if they're only part of a string value

srunner/scenariomanager/actorcontrols/simple_vehicle_control.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenariomanager/timer.py, srunner/tools/openscenario_parser.py
Some small improvements to the OSC simple vehicle controller
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/623)
=> Improved simple OSC vehicle controller for lane changes

Docs/CHANGELOG.md, srunner/tools/openscenario_parser.py
Fixes #625
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/627)
=> Fixed OSC LanePosition handling

README.md
Checklist:
Old link got to a page, but failed to capture css/images, etc.
Github
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/631)
=> Correct the link to the contribution guidelines

Docs/CHANGELOG.md, README.md, requirements.txt, srunner/scenariomanager/actorcontrols/npc_vehicle_control.py, srunner/scenariomanager/actorcontrols/simple_vehicle_control.py, srunner/scenariomanager/actorcontrols/vehicle_longitudinal_control.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/tools/openscenario_parser.py
**WAIT UNTIL THE RELEASE OF CARLA 0.9.10**
Changed set_velocity to set_target_velocity and set_angular_velcoity to set_target_angular_velocity to match the API changes of 0.9.10
* **CARLA version:** 0.9.10 (almost)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/640)
=> Update to 0.9.10 API changes

Docs/CHANGELOG.md, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/647)
=> Release v0.9.10

Docs/CHANGELOG.md, scenario_runner.py, srunner/scenariomanager/actorcontrols/npc_vehicle_control.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/result_writer.py, srunner/scenariomanager/scenario_manager.py, srunner/scenariomanager/weather_sim.py
This series of commits adds an additional command-line option to produce a JSON report file. In contrast to the JUnit XML, the JSON report captures in a machine-readable fashion the individual test criteria for further automated analysis.
Technically, this is implemented analogously to the JUnit XML output, with the same file name pattern.
* **Python version(s):** 3.7.6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/651)
=> JSON report feature

Docs/CHANGELOG.md, srunner/tools/openscenario_parser.py
Fixed OSC TeleportAction within OSC Story
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/674)
=> Fixed OSC TeleportAction within OSC Story

Docs/CHANGELOG.md, srunner/examples/Slalom.xosc
This scenario is meant to test agents for (static) obstacle evasion capability. It consists of some containers placed along the road that should be evaded.
This PR adds an example OpenSCENARIO scenario where the agent has to evade some (static) containers.
Fixes #  
* **Python version(s):** 3.7.6
* **Unreal Engine version(s):** N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/671)
=> Obstacle evasion OpenSCENARIO

Docs/CHANGELOG.md, metrics_manager.py
an integer cast to the port argument was need to instantiate carla-client
Fixes #692 
* **Python version(s):** 3.6.9
* **Unreal Engine version(s):** UE4.24
* **CARLA version:** CARLA-0.9.10
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/693)
=> Fix issue #692

Docs/CHANGELOG.md, srunner/scenarios/route_scenario.py
This PR offers a fix for the case when a route scenario is run without an agent, which currently produces a runtime error since the agent is None.
* **Platform(s):** Ubuntu 20.04.1
* **Python version(s):** 3.8.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/685)
=> Fix route scenario

Docs/CHANGELOG.md, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenariomanager/actorcontrols/actor_control.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenarios/open_scenario.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/704)
=> Added support to place OSC controller impl next to OSC scenario

Docs/CHANGELOG.md, README.md, scenario_runner.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/723)
=> Release of 0.9.11 version

Docs/CHANGELOG.md, Docs/getting_scenariorunner.md
Fixes #734
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/737)
=> Fixed typo causing import error

Docs/CHANGELOG.md, srunner/scenariomanager/actorcontrols/simple_vehicle_control.py, srunner/scenariomanager/actorcontrols/visualizer.py, srunner/tools/openscenario_parser.py
Added a new visualizer class that can be used for all OSC Controllers.
An example is given in the simple_vehicle_control module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/738)
=> Reworked visualizer for OSC Controller

.github/workflows/static_code_check.yml, .pylintrc, srunner/scenariomanager/actorcontrols/visualizer.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/scenario_manager.py, srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/scenarios/maneuver_opposite_direction.py, srunner/scenarios/signalized_junction_left_turn.py, srunner/tools/openscenario_parser.py, srunner/utilities/code_check_and_formatting.sh
Can now be executed under Ubuntu 20.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/750)
=> Updated code and github actions to newer autopep8 and pylint

Docs/CHANGELOG.md, srunner/examples/ObjectCrossing.xml, srunner/scenariomanager/carla_data_provider.py, srunner/scenarios/construction_crash_vehicle.py
Added Construction Scenario Setup
* **Python version(s):** 3.7.9
Unknown
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/744)
=> Added Construction scenario

srunner/tools/openscenario_parser.py
Resolved exception "AttributeError: 'NoneType' object has no attribute
'attributes'" in OpenScenarioParser.
Fixes #753
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/755)
=> Fixed OSC parser issue on Nonetype actor

Docs/CHANGELOG.md, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/result_writer.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py
`create_blueprint()` at the CarlaDataProvider now has a new ***safe*** argument which will perform an additional filter. This is specially useful for the creation of background activity, as it filters out 2 wheeled vehicles (bikes shouldn't be driving through the road), as well as large vehicles (which might cause problems when turning at close turns). As all spawning functions call this `create_blueprint`, they all have had the ***safe_blueprint*** argument added. This is by default False, retaining compatibility with previous versions
Another argument, ***tick***, have also been added to the spawning functions. This allows the spawning of actors without ticking the CARLA server. This is useful when running on sync mode, as in that case, the server tick must be tightly controlled. As a …
=> Extended CarlaDataProvider's spawning functions

Docs/CHANGELOG.md, Docs/openscenario_support.md, srunner/examples/FollowLeadingVehicle.xosc, srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py, srunner/tools/openscenario_parser.py, srunner/tools/scenario_helper.py
In this PR i have changed
1) `RelativeDistanceCondition`: `longitudinal`, `lateral` distance calculation. But I tested this for only roads with left lanes and right lanes, but not sure about junctions.
2) `RelativeRoadPosition` and `RoadPosition` (new implementation): This is tested and work fine for me. If you find any cases where it does not work, let me know, I will fix it.
If anything is not clear in the code let me know, I will try to explain.
I am preparing diagrams for use case and will share it asap.
* **Python version(s):**  3.8
* **Unreal Engine version(s):** -
None, I don't see any conflicts with existing code.
Regards,
Sagar GV
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> RoadPosition and RelativeRoadPosition Implementation 

.pylintrc, Docs/CHANGELOG.md, scenario_runner.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/scenario_manager.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenariomanager/watchdog.py, srunner/scenarios/control_loss.py, srunner/scenarios/open_scenario.py, srunner/scenarios/route_scenario.py, srunner/tools/openscenario_parser.py
This commit should resolve a memory leak during shutdown
Change-Id: I5028234da09e308b99e4009b4bec3aecc30a8935
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/773)
=> Improved shutdown and cleanup behavior

Docs/CHANGELOG.md, srunner/tools/openscenario_parser.py
Fix for OSC RelativeLanePosition
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/785)
=> Fixed handling of OSC RelativeLanePosition

Docs/CHANGELOG.md, scenario_runner.py, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/result_writer.py, srunner/tools/openscenario_parser.py, srunner/tools/route_parser.py, srunner/tools/scenario_helper.py
Using a delay value of '0.0' or '.0' caused an exception
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/787)
=> Fixed exception when using evaluation criteria with OSC

srunner/scenariomanager/actorcontrols/npc_vehicle_control.py, srunner/scenariomanager/actorcontrols/simple_vehicle_control.py, srunner/scenariomanager/carla_data_provider.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/788)
=> Added OSC Property to turn on all vehicle lights

.pylintrc, srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/tools/scenario_helper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/807)
=> Fixed pylint warnings

Docs/creating_new_scenario.md
Just a little change based on currently available examples
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/805)
=> Correction of function names based on examples

srunner/tools/openscenario_parser.py
Convert the target speed to float.
Fixes #  
* **Python version(s):** 3.8.10
* **CARLA version:** 0.9.12 (released version)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/816)
=> Convert the target speed to float

.github/workflows/unit_test.yml, srunner/tests/carla_mocks/README.md, srunner/tests/carla_mocks/agents/navigation/basic_agent.py, srunner/tests/carla_mocks/agents/navigation/behavior_agent.py, srunner/tests/carla_mocks/agents/navigation/behavior_types.py, srunner/tests/carla_mocks/agents/navigation/controller.py, srunner/tests/carla_mocks/agents/navigation/global_route_planner.py, srunner/tests/carla_mocks/agents/navigation/local_planner.py, srunner/tests/carla_mocks/agents/tools/misc.py, srunner/tests/carla_mocks/carla.py, srunner/tests/test_xosc_load.py, srunner/tools/openscenario_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/835)
=> Added simple unittest for XOSC

Docs/CHANGELOG.md, Docs/getting_scenariorunner.md, manual_control.py
The manual control script has been modified.
- It no longer depends on the CARLA version, removing dependencies from the CARLA examples.
- It has also been simplified, removing all world functionalities such as changing weather, map layer, non camera sensors . This avoids confusing the users about its functionality, which is just as an agent for the scenarios.
* **CARLA version:** 0.9.12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/825)
=> Removed CARLA example dependencies

Docs/CHANGELOG.md, srunner/metrics/tools/metrics_parser.py
As the `carla.WheelPhysicsControl` class initialization was changed (adding two new paramters), the metrics module was crashing when trying to initialize this class. By changing the class creation from position to name, this makes the metrics module more robust to future changing while fixing this problem.
* **CARLA version:** 0.9.12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/838)
=> Fix metrics

Docs/CHANGELOG.md, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenarios/opposite_vehicle_taking_priority.py
Actor Flow behavior are now more robust. By using the ConstantVelocityAgent, which forces actors to move at a certain speed, actors that had different dynamics now accelerate and brake in the same way, removing weird behaviors caused by two different vehicles of the actor flow having to distinct physical parameters
EDIT: It needs [this CARLA PR](https://github.com/carla-simulator/carla/pull/4841) to be merged in order to work
Not all possible corner cases have been studied, and the new agent forces the velocity of the vehicles, which might cause weird behaviors in such cases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Improve actor flow scenarios

scenario_runner.py, srunner/examples/ActorFlow.xml, srunner/examples/HighwayCutIn.xml, srunner/examples/RouteObstacles.xml, srunner/scenarioconfigs/scenario_configuration.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py, srunner/scenarios/actor_flow.py, srunner/scenarios/background_activity.py, srunner/scenarios/bycicle_group.py, srunner/scenarios/construction_crash_vehicle.py, srunner/scenarios/follow_leading_vehicle.py, srunner/scenarios/highway_cut_in.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/opposite_vehicle_taking_priority.py, srunner/scenarios/route_obstacles.py, srunner/scenarios/signalized_junction_left_turn.py, srunner/scenarios/signalized_junction_right_turn.py, srunner/tools/background_manager.py, srunner/tools/scenario_helper.py
Changes in Actor Flow, implementation of Accident and Construction, changes to BA
* **Platform(s):** Ubuntu 18
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/863)
=> Changes in Actor Flow, implementation of Accident and Construction, changes to BA

srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenarios/actor_flow.py, srunner/scenarios/background_activity.py
Added a prototype of the CrossingBycicleFlow scenario, where the vehicle is meant to turn at an intersection, but has a bycicle flow at its side, which has to cross
Also, changed the *safe_blueprint* to *filter_type*, as new attributes have been added to the vehicles.
* **Platform(s):** Ubuntu18.01
=> Added urban bicycle flow prototype

Docs/CHANGELOG.md
Added missing CHANGELOG at the `leaderboard-2.0` branch
=> Added CHANGELOG

Docs/CHANGELOG.md, scenario_runner.py, srunner/examples/VehicleOpensDoor.xml, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenarios/background_activity.py, srunner/scenarios/basic_scenario.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/vehicle_opens_door.py, srunner/tools/background_manager.py
Added new scenario, *VehicleOpensDoor*, where a vehicle parked at the side suddenly opens the door, forcing the ego to brake. After a set amount fo time, the adversary will close the door, allowing the go to continue moving
Generalized the *filter_type* at CarlaDataProvider functions for *attribute_filter*, a dictionary.
Improved BA's interaction with crossing actor, no teleporting the actor in front of the ego enough distance as to avoid any interaction.
Separated the route argument into two, `route` for the file path, and `route-id`, for the name of route. The functionaility remains unchanged.
--- …
=> Vehicle opens door

Docs/CHANGELOG.md, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/scenariomanager/traffic_events.py, srunner/scenarios/actor_flow.py, srunner/scenarios/background_activity.py, srunner/scenarios/route_scenario.py, srunner/tools/background_manager.py, srunner/tools/route_manipulation.py
Added a new criteria to check the min speed of the ego vehicle. This is done by comapring its speed with the rest of the vehicles, and can be deactivated at some scenarios can generate congestions / force the ego to break
Additionally, improved the beahvior of the BackgroundActivity at high speed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/883)
=> Added mnimum speed criteria

srunner/routes/ParkingExit.xml, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/scenarios/parking_exit.py
Add Parking Exit scenario. The scenario in which the ego is parked between two vehicles and has to maneuver to start the route.
* **CARLA version:** leaderboard-2.0 branch
1. Need to discuss: the distance leaving for blocking vehicles in front of and behind the parking point. Currently it is configurable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/882)
=> add Parking Exit scenario

srunner/scenarios/actor_flow.py, srunner/scenarios/background_activity.py, srunner/scenarios/vehicle_opens_door.py, srunner/tools/background_manager.py
Several improvements have been made
- Removed an unused parameter at the ActorFlow scenario
- Improved the VehicleOpensDoor scenario.
- Background Activity
- Remove the `extra_radius` at the BackgroundActivity as the new road parameters don't need them anymore
- Changed some of the background manager behavior that change the BA's parameters
- Removed the `direction` argument at the `extent_road_exit_space` function, as this was only meant to work with the route's exit lane
- `leave_space_in_front` has been improved, and it'll now take into account the position of the vehicle in front, to avoid moving them too far away
* **Platform(s):**Ubuntu 18.04
--- …
=> General improvements

Docs/CHANGELOG.md, srunner/routes/leaderboard_2.0_testing.xml, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenarios/background_activity.py, srunner/scenarios/parking_exit.py, srunner/scenarios/route_obstacles.py, srunner/scenarios/vehicle_opens_door.py, srunner/tools/background_manager.py
- Improved ParkingExit scenario by moving the blocking vehicles to the side
- Changed VehicleOpensDoor scenario. Now the expected behavior is for the ego to change to an adjacent lane to avoid the obstacle. Simply waiting will no longer result in a successful scenario.
- Added a new Accident scenario, where the ego now has to invade an opposite lane in orther to surpass it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/888)
=> New LB2.0 scenario improvements

srunner/scenarios/background_activity.py
As the BA keeps spawnign vehicles, relying on each vehicle speed limit is not reliable enough. As susch, they now will be based off the ego's target speed instead
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/893)
=> Background Activity target speed improvements

Docs/CHANGELOG.md, srunner/routes/leaderboard_2.0_testing.xml, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenarios/background_activity.py, srunner/scenarios/highway_cut_in.py
Finished HighwayCutIn scenario. This scenario creates a vehicle at a highway entry lane which is the synchronized to cut into the ego's lane after the jucntion ends. The scenario expects the entry to have an acceleration lane or it won't work
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/892)
=> Added HighwayCutIn scenario

Docs/CHANGELOG.md, srunner/routes/leaderboard_2.0_testing.xml, srunner/scenarios/parking_cut_in.py, srunner/scenarios/parking_exit.py
Added a new scenario, `ParkingCutIn`, where are vehicle parked at the side lane suddenly cuts in front og the ego vehicle.
Changed the `ParkingExit` argument `parking_side_lane`, to `direction`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/894)
=> Added ParkingCutIn scenario

Docs/CHANGELOG.md, srunner/routes/leaderboard_2.0_testing.xml, srunner/scenarios/actor_flow.py, srunner/scenarios/background_activity.py, srunner/scenarios/highway_cut_in.py, srunner/tools/background_manager.py
Add MergerIntoSlowTraffic scenario.   
* **Platform(s): Ubuntu 20.04
* **Python version(s): 3.7
* **Unreal Engine version(s): 4.26
* **CARLA version: leaderboard-2.0 branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/903)
=> Merger into slow traffic

Docs/CHANGELOG.md, srunner/routes/leaderboard_2.0_testing.xml, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenarios/invading_turn.py
1. Add InvadingTurn scenario
2. Add opt_dict to BasicAgentBehavior
Fixes #  
* **CARLA version:** leaderboard-2.0 branch
As discussed in discord, when the scenario is triggered, the simulation will be stuck for a second. 
Since the CarlaDataProvider.get_global_route_planner()  is not merged into the leaderboard-2.0 branch yet, this problem may be solved later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/908)
=> Invading turn

Docs/CHANGELOG.md, srunner/scenariomanager/timer.py, srunner/scenarios/basic_scenario.py, srunner/scenarios/route_scenario.py
Changed how the timeout works at routes. It now starts at a much lower value, but it icnreases every time the ego vehicle advanced through the route
* **Unreal Engine version(s):** CARLA's latest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/914)
=> Improved route's timeout

srunner/routes/leaderboard_2.0_testing.xml, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenariomanager/timer.py, srunner/scenarios/cut_in_with_static_vehicle.py, srunner/scenarios/route_obstacles.py
Some of the most recent scenarios were tested using an old branch, which caused merge issues, breaking them. They are fixed now
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/915)
=> Some scenario fixes

srunner/routes/leaderboard_2.0_testing.xml, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/scenarios/actor_flow.py, srunner/scenarios/background_activity.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/parking_exit.py
Added a vehicle at the `ParkingExit` scenrio, improving the initial configuration
Added a crossing angle to `DynamicObjectCrossing` so that the pedestrian can now cross the road in a non-perpendicular movement
Fixed some errors caused by a previous merge at `YieldToEmergencyVehicle` and `MergerIntoSlowTraffic`.
At roads, vehicles part of the BackgroundActivity that are behind the ego will now have increased speed to try to catch up to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/916)
=> New scenario improvements

srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/scenariomanager/traffic_events.py
This PR adds the attribute `frame` to the traffic event. This allows to sort traffic events of different categories by time.
* **Unreal Engine version(s):** CARLA fork
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/918)
=> Added frame to traffic events

srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/lights_sim.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/scenarios/actor_flow.py, srunner/scenarios/background_activity.py, srunner/scenarios/construction_crash_vehicle.py, srunner/scenarios/cross_bicycle_flow.py, srunner/scenarios/cut_in_with_static_vehicle.py, srunner/scenarios/highway_cut_in.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/parking_cut_in.py, srunner/scenarios/parking_exit.py, srunner/scenarios/pedestrian_crossing.py, srunner/scenarios/route_obstacles.py, srunner/scenarios/vehicle_opens_door.py, srunner/scenarios/yield_to_emergency_vehicle.py, srunner/tools/openscenario_parser.py, srunner/tools/scenario_helper.py
3rd batch improvements to the scenarios
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/926)
=> Leaderboard 2.0 3rd batch of improvements

srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py, srunner/scenarios/actor_flow.py, srunner/scenarios/background_activity.py, srunner/scenarios/blocked_intersection.py, srunner/scenarios/construction_crash_vehicle.py, srunner/scenarios/control_loss.py, srunner/scenarios/cut_in_with_static_vehicle.py, srunner/scenarios/invading_turn.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/parking_exit.py, srunner/scenarios/pedestrian_crossing.py, srunner/scenarios/route_obstacles.py, srunner/scenarios/signalized_junction_left_turn.py, srunner/scenarios/vehicle_opens_door.py, srunner/scenarios/yield_to_emergency_vehicle.py, srunner/tools/background_manager.py, srunner/tools/scenario_helper.py
More improvements to the new scenarios. These include:
- Added a variable actor flow to the route obstacles scenarios with opposite direction invasion
- Readded the *ControlLoss* noise
- Minor modifications to the *YieldToEmergencyVehicle* scenario to make it more robust
- Fixed some issues with the BackgroundActivity interfering with the *InterurbanActorFlow* scenario
- Removed the obstackles at *BlockedIntersection* as they were not very reliable.
- Fixed bug causing the route obstacles scenarios to sometimes never end
- *InvadingTurn* will now be an actor flow
- Added *VehicleTurningRoutePedestrian*, a variation of *VehicleturningRoute* that uses a pedestrian instead of a bicycle
- Added more pedestrians to *PedestrianCrossing*
- RunningRedLightTest and RunningStopTest have been made …
=> Another batch of new scenario improvements

srunner/scenariomanager/lights_sim.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/scenariomanager/timer.py, srunner/scenarios/basic_scenario.py, srunner/scenarios/blocked_intersection.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/parking_exit.py, srunner/scenarios/pedestrian_crossing.py, srunner/scenarios/route_scenario.py
- Fine tuned the lights behavior for routes
- CollisionTest will now ignore collision if the actor is stopped
- Change the behavior of some pedestrian scenarios to patch a CARLA issue with the pedestrian caused when setting them to dormant at large maps. To patch it, the pedestrians now track the ego position, perirodically repositioning until its scenario starts  
- The minimum sped criteria will now subdivide the route in checkpoints, checking them independently
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/930)
=> Several minor changes

srunner/scenarios/basic_scenario.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/opposite_vehicle_taking_priority.py, srunner/scenarios/parking_cut_in.py, srunner/scenarios/parking_exit.py, srunner/scenarios/pedestrian_crossing.py, srunner/scenarios/vehicle_opens_door.py
Fixed bug pedestrians and parked vehicles. Parked vehicles are now spawned at runtime in the leadeboard.
Fixes #  
* **Platform(s):** UBuntu 18.04
* **Unreal Engine version(s):** CARLA0's
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/933)
=> Fixed bug pedestrians and parked vehicles

Docs/CHANGELOG.md, srunner/scenariomanager/actorcontrols/simple_vehicle_control.py
Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/941)
=> Add waypoint reached threshold as scenario parameter

srunner/scenariomanager/lights_sim.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py, srunner/scenarios/actor_flow.py, srunner/scenarios/background_activity.py, srunner/scenarios/blocked_intersection.py, srunner/scenarios/construction_crash_vehicle.py, srunner/scenarios/control_loss.py, srunner/scenarios/cross_bicycle_flow.py, srunner/scenarios/cut_in_with_static_vehicle.py, srunner/scenarios/highway_cut_in.py, srunner/scenarios/invading_turn.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/opposite_vehicle_taking_priority.py, srunner/scenarios/parking_cut_in.py, srunner/scenarios/pedestrian_crossing.py, srunner/scenarios/route_obstacles.py, srunner/scenarios/signalized_junction_left_turn.py, srunner/scenarios/signalized_junction_right_turn.py, srunner/scenarios/yield_to_emergency_vehicle.py, srunner/tools/background_manager.py
Fixed the known bugs for the new scenarios
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/950)
=> Lb 20 improvements

srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py, srunner/scenarios/basic_scenario.py
Implement runtime initialization.
Related: [https://github.com/carla-simulator/leaderboard/pull/150](leaderboard/pull/150)
- Check route_mode before init env
- Add _runtime_init_flag to control the ticking in runtime_init mode
- Fix: add location None check in DriveDistance
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/984)
=> Runtime initialization

requirements.txt, scenario_runner.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/result_writer.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py, srunner/scenarios/background_activity.py, srunner/scenarios/basic_scenario.py, srunner/scenarios/route_scenario.py, srunner/scenarios/vehicle_opens_door.py, srunner/tools/background_manager.py
This PR updated the Leaderboard 2.0  branch with teh new version. Includes: 
- Fixed the issue where calling an actor's transform / location to CDP returned None during the first frame
- Added runtime intiialization logic, used by the LB to initialize scenarios during the simulation, instead of all of them at the same time
- Improved the destruction of sensors created by the scenarios
- Improved the teleporting of actors, removing their momentun
- Improved the BackgroundActivity behavior when the map had lanes that start in the middle of a road
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/995)
=> New version Leaderboard 2.0

srunner/scenariomanager/lights_sim.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py
Added a couple of try catch in case the TM destroyed an actor
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/1036)
=> Added some tries in case the TM destroys a vehicle

srunner/scenariomanager/carla_data_provider.py
Fixes: `request_new_batch_actors` uses the `spawn_point` of the last actor for all actors, there should be one per actor.
https://github.com/carla-simulator/scenario_runner/blob/f3a84077a632421b43e90aa7bf4b307b3fb745aa/srunner/scenariomanager/carla_data_provider.py#L751-L759
* **Python version(s):** 3.10
* **CARLA version:** 9.15
Cannot see any.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/1068)
=> [leaderboard-2.0] Fix: wrong initial transform when using CDP's `request_new_batch_actors` 

srunner/metrics/tools/metrics_parser.py
Fixes #1044
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/1076)
=> Fixed metrics wheel parser

scenario_runner.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/1082)
=> Update minimum CARLA version to 0.9.14

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/1130)
=> Include 0.9.14 carla release as compatible with scenario runner 0.9.13

srunner/scenariomanager/carla_data_provider.py
Adds simple public method to access `CarlaDataProvider._blueprint_library`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/1112)
=> Add public method to access blueprint library on CDP

srunner/examples/follow_trajectory.osc, srunner/osc2_stdlib/path.py, srunner/scenariomanager/actorcontrols/vehicle_teleport_control.py, srunner/scenariomanager/actorcontrols/vehicle_velocity_control.py
Some fixes for the teleport and velocity control when going at low speeds
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/1150)
=> [OSC2.0] Trajectory fixes for slow speeds

srunner/scenariomanager/actorcontrols/vehicle_velocity_control.py
Fixed an issue causing trajectories that end in a full stop to make the vehicle rotate in place
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/1151)
=> Fixed angular speed at stopped end trajectories
