carla-simulator/scenario_runner

Docs/getting_started.md, Docs/list_of_scenarios.md, ScenarioManager/atomic_scenario_behavior.py, ScenarioManager/atomic_scenario_criteria.py, Scenarios/control_loss.py, scenario_runner.py
* Added new scenario in control_loss.py
* Added new atomic SteerVehicle
* Added new criteria ReachedLocationTest
* Added new scenario to list in scenario_runner.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/7)
=> Implementation of Traffic Scenario 01

ScenarioManager/atomic_scenario_behavior.py, ScenarioManager/result_writer.py, Scenarios/control_loss.py, Scenarios/follow_leading_vehicle.py, Scenarios/no_signal_junction_crossing.py, Scenarios/object_crash_intersection.py, Scenarios/object_crash_vehicle.py, Scenarios/opposite_vehicle_taking_priority.py
- Updated all scenarios to use Lincoln MKZ as ego vehicle
- Removed unnecessary timeouts from scenarios
- Updated VehicleTurningRight/Left scenarios to sync arrival times
- Resolved pylint issues
Checklist:
* **Python version(s):** Python 2.7 and 3.5
* **Unreal Engine version(s):** 4.19
* **CARLA version:** 0.9.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/20)
=> Various scenario updates

scenario_runner.py, srunner/challenge/autoagents/DummyAgent.py, srunner/challenge/challenge_evaluator.py, srunner/challenge/envs/sensor_interface.py
It is reasonable for the agents to also have access to its current forward speed. 
However, speed, right now is not defined as a sensor, but as part of the vehicle
transformation.
This PR adds a "sensor", coded in python, that asynchronously provide speeds.
The sensor can be add to an agent as follows:
['sensor.speedometer', {'reading_frequency': 25},
'speed'
],
Also added a traceback to print the full exception for the scenario manager.
line 234. I think the exception catch there is too broad and make debug a bit
hard.
* **Platform(s):**ubuntu 16.04
* **Python version(s):**  3.5
* **CARLA version:**  CARLA 0.9.3
One problem is that we have to set a sampling rate that normally is different than the sampling rate of the other sensors collected in CARLA.
--- …
=> Pseudo velocity sensor

CHANGELOG.md, srunner/scenariomanager/atomic_scenario_behavior.py
* Prepared a behaviour to destroy an actor
* Useful when actor is required to be destroyed from behaviour tree
This will help to destroy actors from the tree, which can be used for end conditions also.
* **Platform(s):**  Linux 18.04
Since this behaviour uses destroy method possibility of getting warnings that actor is already destroyed when final cleanup runs.  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/91)
=> Adding Destroy Atomic Behaviour

srunner/scenariomanager/carla_data_provider.py
* Added a check to set autopilot only if 'Actor' object has 'set_autopilot' attribute (set_autopilot is applicable only for the vehicle).
* **Platform(s):** linux 18.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/98)
=> Set autopilot only if its a vehicle in Carla data provider

CHANGELOG.md, srunner/scenariomanager/atomic_scenario_behavior.py, srunner/scenariomanager/atomic_scenario_criteria.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenarios/follow_leading_vehicle.py, srunner/scenarios/maneuver_opposite_direction.py, srunner/scenarios/no_signal_junction_crossing.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/opposite_vehicle_taking_priority.py, srunner/scenarios/other_leading_vehicle.py, srunner/scenarios/scenario_helper.py, srunner/scenarios/signalized_junction_left_turn.py, srunner/scenarios/signalized_junction_right_turn.py
To avoid traffic jams due to not moving actors in not yet triggered are already passed scenarios, an "appear" behavior and an destroy behavior was added to all scenarios.
The appear behavior is reached by adjusting the actor transform. At the beginning, all actors are spawned under the surface, and only upon triggering the scenario, the actors appear. 
Checklist:
* **CARLA version:** 0.9.4+
Some scenarios look a bit strange now, due to the sudden appearance of actors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/112)
=> Added "appear" and detroy behaviors to all scenario actors

srunner/scenariomanager/atomic_scenario_behavior.py, srunner/scenariomanager/atomic_scenario_criteria.py, srunner/scenariomanager/carla_data_provider.py
The next() method for waypoints may return None. This special case has
to be detected and handled properly.
Checklist:
* **CARLA version:** 0.9.4+
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/127)
=> Fixed all next()-calls in scenariomanager module

srunner/challenge/challenge_evaluator_routes.py, srunner/scenariomanager/atomic_scenario_criteria.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenarios/follow_leading_vehicle.py, srunner/scenarios/no_signal_junction_crossing.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/opposite_vehicle_taking_priority.py, srunner/scenarios/other_leading_vehicle.py, srunner/scenarios/signalized_junction_left_turn.py, srunner/scenarios/signalized_junction_right_turn.py, srunner/testing/test_scenario_building.py
This pr changes the start position of scenarios to a deeper level.
I also fixed a bug on timeout initialization. 
Current Status:
Town 01 Spawn all scenarios
Town 03-Town04 Fails because there are start positions on intersections
* **Platform(s):** ubntu
* **CARLA version:** nightly from las friday.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/136)
=>  changing the start positions

srunner/scenariomanager/atomic_scenario_behavior.py
Added code to reset actor velocity and angular velocity to 0 before moving the actors above ground.
* **Unreal Engine version(s):** 
* **CARLA version:** Carla overnight build of monday
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/139)
=> Resetting actor kinematics on ActorTransformSetter

CHANGELOG.md, FAQ.md, setup_environment.sh, srunner/challenge/challenge_evaluator_routes.py, srunner/challenge/test_challenge_route.py, srunner/scenariomanager/atomic_scenario_behavior.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenarios/basic_scenario.py, srunner/tools/config_parser.py, srunner/tools/scenario_helper.py, srunner/utilities/code_check_and_formatting.sh
A new atomic behavior InTriggerDistanceToLocationAlongRoute was added.
As the name indiciates, the behavior calculates the distance to a given
location along a given route.
Therefore, a new method was added to tools/scenario_helper.py to
calculate the distance along a given route: get_distance_along_route()
The new behavior is used in the BasicScenario class to trigger a
scenario.
*Fixes* the trigger issue if a scenario is not directly "located" on the ego vehicle route
*Other edits*
- Added FAQ
- Updated setup script to match CARLA 0.9.5
Checklist:
* **Python version(s):** Python 3.5 , 2.7
* **CARLA version:** 0.95
If there is a loop in the route, a scenario is only triggered on the first pass of the loop segment.
--- …
=> Added methods to calculate distances along route

srunner/challenge/challenge_evaluator_routes.py, srunner/scenariomanager/atomic_scenario_behavior.py, srunner/scenarios/basic_scenario.py, srunner/scenarios/object_crash_vehicle.py
We changed bikes from TS3 to Walkers
Changed threshold for scenario triggering.
* **CARLA version:** 9.5 nightly
The physics could not be deactivated for the walkers. After you reactivate they
fall of the ground see https://github.com/carla-simulator/carla/issues/1513
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/167)
=> Changing all the bikes of TS3 to walkers

scenario_runner.py, srunner/challenge/challenge_evaluator_routes.py, srunner/challenge/test_challenge_route.py, srunner/scenariomanager/carla_data_provider.py
The following fixes are included
- Reset of py_tree states to INVALID --> Next run does not skip execution
- Removal of destructor calls for scenarios --> Proper actor cleanup
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/177)
=> Fixed scenario cleanup when running sequences or repetitions

srunner/scenariomanager/atomic_scenario_behavior.py
If the CARLA actor, the behavior ActorTransformSetter() refers to, is
missing, the behavior crashed. An additional check is now added. In case
the actor was destroyed, the behavior returns a failure.
Change-Id: Ie66d594359022f95b232dd8a55c8a2ae65f35772
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/180)
=> Fixed crash in ActorTransformSetter()

srunner/scenariomanager/carla_data_provider.py, srunner/scenarios/basic_scenario.py
The background class already remove actors, but they are not erased from the other actor list.
Added a check to see if the actor is already removed before removing it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/195)
=> Avoid removing actors twice.

srunner/scenarios/control_loss.py
Title says everything
* **CARLA version:** Latest master
I think the behavior should end after the last jitter, however it continues for a certain distance. Therefore, I reduced the distance for now. Please merge, if you agree. Otherwise, the end_noise behavior should be moved to an earlier place in the behavior sequence.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/202)
=> Reduced duration (distance) of control loss scenario

srunner/scenariomanager/atomic_scenario_criteria.py
A red traffic light that is run, is only counted once.
* **Python version(s):** 2.7, 3.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/250)
=> Fixed RunningRedLightTest: Count each light only once

srunner/scenariomanager/atomic_scenario_behavior.py
TrafficLightManipulator was using distance of the ego-car to the actual traffic light pole
instead of distance between the ego-car and the trigger area of the traffic light.
Fix: bug in trafficLightManipulator
TrafficLightManipulator was using distance of the ego-car to the actual traffic light pole
instead of distance between the ego-car and the trigger area of the traffic light.
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/257)
=> Fix: bug in trafficLightManipulator

srunner/challenge/Dockerfile.ros
- No longer installs the CARLA PythonAPI egg but
adds it to the PYTHONPATH for dynamical usage and
to support replacement of the PythonAPI files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/261)
=> Replace installing Python egg with dynamic usage

srunner/scenariomanager/atomic_scenario_criteria.py
15m instead of 10m to cope with multi-lane highways as in Town04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/263)
=> Increased value for maximum route deviation to 15m

srunner/scenariomanager/atomic_scenario_criteria.py
A sidewalk should only count as invasion not as collision
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/270)
=> Removed collisions with sidewalk as failures

traffic_manager/source/include/ActorStateCallable.hpp, traffic_manager/source/include/ActorStateStage.hpp, traffic_manager/source/include/CarlaDataAccessLayer.hpp, traffic_manager/source/include/FeederMessage.hpp, traffic_manager/source/include/InMemoryMap.hpp, traffic_manager/source/include/PipelineCallable.hpp, traffic_manager/source/include/PipelineMessage.hpp, traffic_manager/source/include/RegisteredActorMessage.hpp, traffic_manager/source/include/SimpleWaypoint.hpp, traffic_manager/source/src/ActorStateCallable.cpp, traffic_manager/source/src/ActorStateStage.cpp, traffic_manager/source/src/PipelineCallable.cpp, traffic_manager/source/test/main.cpp
Traffic Manager API with Pipeline, Feeder and ActorState classes.
Fixes #  
* **CARLA version:** ...0.9.4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/274)
=> Traffic Manager API

CHANGELOG.md, Docs/creating_new_scenario.md, scenario_runner.py, srunner/challenge/challenge_evaluator_routes.py, srunner/configs/FreeRide.xml, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/result_writer.py, srunner/scenariomanager/scenario_manager.py, srunner/scenarios/background_activity.py, srunner/scenarios/basic_scenario.py, srunner/scenarios/control_loss.py, srunner/scenarios/follow_leading_vehicle.py, srunner/scenarios/freeride.py, srunner/scenarios/maneuver_opposite_direction.py, srunner/scenarios/master_scenario.py, srunner/scenarios/no_signal_junction_crossing.py, srunner/scenarios/object_crash_intersection.py, srunner/scenarios/object_crash_vehicle.py, srunner/scenarios/opposite_vehicle_taking_priority.py, srunner/scenarios/other_leading_vehicle.py, srunner/scenarios/signalized_junction_left_turn.py, srunner/scenarios/signalized_junction_right_turn.py, srunner/scenarios/trafficlight_scenario.py, srunner/tools/config_parser.py
As one of CARLA's key features is the support for multiple ego vehicles, this PR brings in this feature also for the scenario execution. Multiple ego vehicles can be specified in the configuration file (XML) and identified via their unique role names. A simple example for a scenario using multiple ego vehicles is provided.
Other changes are:
* Added additional command line options for the scenario_runner.py
- --waitForEgo: Wait and connect 
- --outputDir: User defined output folder
- --configFile: External XML file
- --additionalScenario: External scenario definition (python class)
Checklist:
Fixes #291 (There is a new commandline option to disable reloading the CARLA world)
None
---
This …
=> Support for multiple ego vehicles

srunner/scenariomanager/carla_data_provider.py
Newer CARLA versions can cause a collision upon vehicle spawning when
the spawn point is on ground level.
Fixes #305 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/307)
=> Fixed spawn issue (collision with ground) for newer CARLA versions

CHANGELOG.md, Docs/openscenario_support.md, scenario_runner.py, srunner/configs/CyclistCrossing.xosc, srunner/configs/FollowLeadingVehicle.xml, srunner/configs/FollowLeadingVehicle.xosc, srunner/scenarios/open_scenario.py, srunner/tools/config_parser.py, srunner/tools/openscenario_parser.py
Weather conditions can now be set in OpenSCENARIO or through
scenarios defined in Python (via XML)
Example for old XML style is provided in FollowLeadingVehicle.xml
Checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/332)
=> Add support to set/change weather conditions for a scenario

CHANGELOG.md, srunner/scenariomanager/atomic_scenario_behavior.py, srunner/scenarios/follow_leading_vehicle.py, srunner/scenarios/maneuver_opposite_direction.py, srunner/scenarios/opposite_vehicle_taking_priority.py, srunner/scenarios/signalized_junction_left_turn.py, srunner/scenarios/signalized_junction_right_turn.py
The interface of the WaypointFollower behavior used km/h instead of m/s
Checklist:
Fixes #339 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/343)
=> Fixed usage of km/h instead of m/s for WaypointFollower behavior

srunner/scenarios/object_crash_vehicle.py
Walker was not moving due to wrong start location of the trigger
condition.
Addresses #323
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/346)
=> Fixed walker behavior in DynamicObjectCrossing (TS03) scenario

srunner/scenarios/object_crash_intersection.py
Adversary was not moving due to wrong start location of the trigger
condition.
Addresses #323 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/347)
=> Fixed adversary start transform in VehicleTurningRight/Left (TS04) scenarios

CHANGELOG.md, srunner/scenarios/object_crash_vehicle.py
Instead of requesting an actor of type walker* the type walker.* has to
be used to avoid using the 'controller.ai.walker' by accident.
Checklist:
Fixes #349 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/351)
=> Fixed walker selection in DynamicObjectCrossing

CHANGELOG.md, srunner/scenariomanager/carla_data_provider.py
The spawn_point parameter of CarlaActorPool.setup_actor() should be
const, but do to call-by-reference it was mistakenly modified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/358)
=> Fixed spawn_point modification in CarlaActorPool.setup_actor()

srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py, srunner/scenarios/open_scenario.py, srunner/tools/openscenario_parser.py
AfterTermination rule attributes are now respected
When an element ends, it tries to accurately determine whether it ended or cancelled (or in some cases, both)
The conditions will wait for the correct type of termination before evaluating as true
Addresses #378
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/380)
=> Aftertermination rules

Docs/openscenario_support.md, srunner/scenarioconfigs/openscenario_configuration.py
Instead of only providing the CARLA town name, it is also now possible to use
the fully qualified path. This brings us closer to the standard.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/391)
=> Enabled use of fully qualified path for roadnetwork in OpenSCENARIO

CHANGELOG.md, Docs/openscenario_support.md, srunner/examples/CyclistCrossing.xosc, srunner/examples/FollowLeadingVehicle.xosc, srunner/examples/LaneChangeSimple.xosc, srunner/examples/PedestrianCrossingfront.xosc, srunner/scenarioconfigs/openscenario_configuration.py, srunner/tools/openscenario_parser.py
OpenSCENARIO definition is for right-hand coordinate systems. CARLA however uses a left-hand system. Hence, a conversion is necessary. The default behavior will be to map from right-hand to left-hand. To avoid this mapping, the scenario name has to start with "CARLA:"
Checklist:
If the OpenSCENARIO was designed for CARLA, and the name is not adjusted to start with "CARLA:" to positions will be wrong after this commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/396)
=> Extended OSC support to handle right and left-hand coordinate systems

srunner/examples/LaneChangeSimple.xosc, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/tools/openscenario_parser.py, srunner/tools/scenario_helper.py
The distance parameter for the LaneChange action corresponds to the total length of the lane change (from lane a to lane b). This was updated in this PR.
Checklist:
* **Platform(s):**  Ubuntu 16.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/402)
=> Updated LaneChange distance for OpenSCENARIO

srunner/scenarios/open_scenario.py
To avoid that different sequences in OpenSCENARIO share the same
blackboard entry (to achieve a one-shot behavior), sequences are now
identified via their name plus a leading "Seq:" on the blackboard.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/407)
=> Added sequence identifier for OpenSCENARIO

srunner/scenarioconfigs/openscenario_configuration.py
To support relative positioning of actors allowed by OpenSCENARIO, the
CARLA world is (pre)-loaded inside the OpenScenarioConfiguration()
constructor. However, if there are other clients already connected to
CARLA, this can cause issues. Therefore, the map is now only loaded, if
it is different from the current CARLA map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/410)
=> Fixed issue due to pre-loading the map in OpenScenarioConfiguration

srunner/scenarios/open_scenario.py
The access to the CARLA actor attributes (here: rolename) has only
to happen, if there is an initial speed provided for this actor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/416)
=> Fixed wrong actor rolename access in OSC init_behavior

Docs/CHANGELOG.md, srunner/scenarios/route_scenario.py
Having multiple scenarios with the same name along a route caused the
issue that all scenarios with the same name were terminated, once the
first of these scenarios finished (Issue #422)
To fix this issue, unique oneshot-ids are now used.
Fixes #422
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/423)
=> Fixed oneshot behavior in route scenarios (#422)

Docs/CHANGELOG.md, srunner/challenge/envs/sensor_interface.py
CARLA API changed from GnssEvent to GnssMeasurement
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/431)
=> Fixed Gnss sensor interface

.travis.yml, Docs/getting_started.md, requirements.txt
All later versions do no longer support Python 2.7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/439)
=> Fixed xmlschema version to 1.0.18

Docs/CHANGELOG.md, srunner/scenarioconfigs/openscenario_configuration.py, srunner/tools/openscenario_parser.py
- Extended OSC support with handling of MiscObjects (e.g. barriers)
- Reworked traffic signal handling. The name is used as unique
identifier. If the ID should be used, the name has to start with "id=",
if the position should be used, it has to start with "pos=" followed by
x,y.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/438)
=> Added support for MiscObjects and better traffic signal handling for OSC

Docs/CHANGELOG.md, srunner/scenarios/control_loss.py
Transform of debris is set to default position right after actor
creation to avoid getting stuck behind a "flying" debris
* **Platform(s):**  Ubuntu
* **Python version(s):** 2.7 / 3.5
* **CARLA version:** 0.9.7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/441)
=> Fixed spawning of debris for ControlLoss scenario (Scenario01)

Docs/CHANGELOG.md, scenario_runner.py, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/scenario_manager.py, srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py, srunner/scenarios/basic_scenario.py, srunner/scenarios/open_scenario.py, srunner/tools/openscenario_parser.py
Repetitions in OpenSCENARIO were not properly working. Reworked the repetition
handling by three major changes:
- Not copy py_tree elements, this will cause problems due to references in Python
- Replaced get_py_tree_path with get_xml_path, as the first was not working properly
- Avoid using ":" in py_tree behavior names, as this may break py_trees
Fixes #443
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/447)
=> Fixed repetitions in OpenSCENARIO (Fixes #443)

Docs/CHANGELOG.md, srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/scenarios/master_scenario.py
**InRouteTest** has been made more forgiving.
**1.** The default max distance has been doubled, to 30 meters
**2.** In addition, while further than 15 meters, the route distance traveled is computed and if it is higher than 30% of the routes total, the criteria fails
The two distances (15 and 30 m) are parameters of the criteria
* **CARLA version:** 0.9.7
InRouteTest might be too forgiving sometimes as it is partially dependent on the route distance.
Route distance might not be reliable when far away from close turns.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_ru …
=> New InRouteTest

srunner/scenarios/route_scenario.py
The way routes are initialized has been changed:
1. Background activity is now spawned after the scenarios
2. A tick is done to the world every several spawned scenarios.
The second change is meant to ease the initialization of the route scenario and while it doesn't increase its performance, the spawning is done through several frames, instead of everything at the same time, **reducing the chances of Unreal crashing**. The first one also helps as the **TM was working** while the scenarios were being created, controlling the background activity **even before the scenarios were all spawned**, which translated into wasted computational time.
* **CARLA version:** 0.9.7.3
--- …
=> Changed route initialization

Docs/CHANGELOG.md, srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py
Fixed wrong StandStill behavior which return SUCCESS immediatly on a
standing actor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/479)
=> Fixed StandStill behavior

Docs/CHANGELOG.md, scenario_runner.py, srunner/challenge/autoagents/agent_wrapper.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/scenario_manager.py, srunner/scenariomanager/watchdog.py, srunner/scenarios/basic_scenario.py, srunner/scenarios/route_scenario.py
A watchdog is added to the ScenarioManager to detect and handle internal
timeouts as well as CARLA/Unreal crashes. Upon these a KeyboardInterrupt
is raised to trigger a clean shutdown of ScenarioRunner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/475)
=> Added watchdog to ScenarioManager to handle timeouts and CARLA crashes

Docs/CHANGELOG.md, README.md, srunner/examples/FollowLeadingVehicle.xosc, srunner/scenarioconfigs/openscenario_configuration.py, srunner/tools/openscenario_parser.py
Positions can now be set with the help of OpenDRIVE roadID and laneID,
offset and s.
Requires CARLA 0.9.8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/483)
=> Extended OpenSCENARIO position handling with roadID and laneID

Docs/CHANGELOG.md, Docs/openscenario_support.md, srunner/examples/CatalogExample.xosc, srunner/examples/catalogs/EnvironmentCatalog.xosc, srunner/scenarioconfigs/openscenario_configuration.py
This takes advantage of the new nighttime setting in CARLA 0.9.8. If the TimeOfDay tag is set between 22:00 and 4:00, it will be nighttime. 4-6 and 20-22 are sunset, and everything in between is normal daytime.
* **Python version(s):** 3.6.9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/485)
=> OpenSCENARIO Support for TimeOfDay

Docs/CHANGELOG.md, srunner/scenarios/object_crash_vehicle.py, srunner/tools/scenario_helper.py
_Problems:_
Spawning problem of the vending machines at DynamicObjectCrossing, partially spawning inside the driving lanes
_Previous Behavior:_
- From the trigger position, get the rightest lane (loop at __initialize_actors_)
- Advance a certain distance from this trigger position (_get_location_in_distance_from_wp_ at _scenario_helper_)
- Calculate spawn point of the vending machine + pedestrian, given by an offset (__calculate_base_transform_)
- Spawn both actors
_Changes:
- For consistency, now the rightest driving / parking lane is calculated, which helps simplify the offset calculus. 
- This advancement was previously stopped by junctions. This caused problems at false junction (barns at rural areas of Town07 and 09, so a flag has been added)
- Modified a constant _k_ of the offset, …
=> Fixed bugs scenario DynamicObjectCrossing

Docs/CHANGELOG.md, srunner/scenarios/object_crash_intersection.py, srunner/tools/scenario_helper.py
_Problems:_
Spawning bugs of the bicycles at VehicleTurning, when part of a route.
_Previous Behavior:_
- From the trigger position, advance until after the junction
- Get the rightest lane
- Advance a certain distance from this trigger position
- Calculate spawn point of the bycicle, given by an offset
- Spawn actors
_Changes_:
- Removed a condition that caused the junction loop to not correctly stop after a junction.
- This loop has been changes for routes. Now this loop follows the route, instead of calculating the next waypoint.
- Now the advancement is done before the rightest lane is searched as junction waypoints (and those very nearby) have no right lanes.
- For consistency, now the rightest driving / parking lane is calculated, which helps simplify the offset calculus. This loop …
=> Fixed bugs scenario VehicleTurning

Docs/CHANGELOG.md, scenario_runner.py, srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py
**Problem:** Bug causing the simulation to freeze after running a route scenario.
**Solution:** Synchronous mode is now removed when the simulation ends (either normally or via manual interruption)
None?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/486)
=> Fixed simulation end freeze bug

Docs/CHANGELOG.md, srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/scenarios/master_scenario.py
This PR adds a new atomic criteria to routes, ActorSpeedAboveThreshold. This criteria checks if the ego-vehicle has been standing still for more that a given amount of time (currently set to 90 seconds) and if so, stops the simulation.
None?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/505)
=> Added a new criteria: ActorSpeedAboveThreshold

Docs/CHANGELOG.md, scenario_runner.py, srunner/challenge/routes_training.xml, srunner/examples/ChangeLane.xml, srunner/examples/CutIn.xml, srunner/examples/FollowLeadingVehicle.xml, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenarioconfigs/route_scenario_configuration.py, srunner/scenarioconfigs/scenario_configuration.py, srunner/tools/route_parser.py, srunner/tools/scenario_config_parser.py
The way routes compute the weather of the simulation has been changed to allow the user to decide the weather of each route.
To do so, the _weather_ attribute has to be added to the .xml file of the route, as a child of the _route_ attribute, along with the parameter values:
If none is chosen by the user, the default is a sunny midday (instead of the map's default one)
None?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/508)
=> Routes now have their weather as a possible parameter

Docs/CHANGELOG.md, scenario_runner.py, srunner/examples/FollowLeadingVehicle.xosc, srunner/examples/LaneChangeSimple.xosc
`setting.fixed_delta_seconds = 1.0 / self.frame_rate` has been moved inside the agent check, as it was being set even in asynchronous mode, causing the simulation to run faster than in real time.
Fixes #494
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/509)
=> Fix to scenarios running faster than real time

.travis.yml, Docs/CHANGELOG.md, requirements.txt, scenario_runner.py, srunner/examples/ChangingWeather.xosc, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenariomanager/scenario_manager.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenariomanager/weather_sim.py, srunner/scenarios/basic_scenario.py, srunner/scenarios/open_scenario.py, srunner/tools/openscenario_parser.py
* Enabled weather simulation/animation
* Reworked handling of weather and road friction:
- Moved from scenario_runner into BasicScenario class, as these are
scenario dependent features
* ScenarioManager update:
- WeatherBehavior as new parallel behavior among timeout and the
desired scenario behavior itself
- Added WeatherSim module to allow animating the sun position over time
w.r.t the CARLA reference position and the provide datetime in UTC
* New behavior atomics:
- WeatherBehavior to simulate weather over time
- UpdateWeather to update weather to a new setting, e.g. sun to rain
- UpdateRoadFriction to update the road friction while running
* BasicScenario class update:
- Added _initialize_environment() method, which can be overloaded in
user-defined scenarios
* OpenSCENARIO 1.0 …
=> Reworked weather and road friction handling

Docs/CHANGELOG.md, srunner/scenarios/basic_scenario.py
Fixed a bug at BasicScenario. A length check has been added to the *_initialize_actors* to avoid raising the exceptions when no other actors are present (for example, running routes with no background activity).
* **Platform(s):** Ubutnu 18.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/530)
=> Fixed bug at BasicScenario's _initialize_actors

srunner/scenariomanager/result_writer.py, srunner/scenariomanager/scenarioatomics/atomic_criteria.py
Fixed bug causing the output functionality when running routes.
The output decides whether or not a criteria has failed by its *test_status* variable. This variable is automatically changed at the *terminate* function of *Criterion*. The problem was caused by some criterias overwriting this function but not calling its counterpart at *Criterion*.
Also, the table size has been adjusted, as the addition of ActorSpeedAboveThreshold was breaking it 
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/533)
=> Fixed output error

Docs/CHANGELOG.md, srunner/autoagents/autonomous_agent.py
Downsample reduced from 32m to 1, as our agents were unable to correctly turn + this feature was made for the challenge. It might be removed / exposed to the user in a later PR
* **Platform(s):** Ubtuntu 18.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/531)
=> "Removed" downsample

Docs/CHANGELOG.md, scenario_runner.py
This PR changes how ScenarioRunner reads the example scenarios
**Previously:** The scenario classes were imported at ScenarioRunner and read through _globals()_.
**Now:** Similar to how the configuration files at _srunner/examples_ are read, SR grabs all the files at the _srunner/scenarios_ folder, adds the path given by the _additionalScenario_ argument and checks if the scenario class is inside those folders.
**Improvements:** Two improvements derive from this change:
1. We no longer need to import the scenario classes at SR, as they are automatically read.
2. As all scenarios at the _srunner/scenarios_ folder will be automatically read, users can put their custome scenarios there and forget about the _additionalScenario_ argument.
* **Python …
=> Changed how SR reads the .py files

Docs/CHANGELOG.md, Docs/openscenario_support.md, scenario_runner.py, srunner/examples/CatalogExample.xosc, srunner/examples/ChangingWeather.xosc, srunner/examples/CyclistCrossing.xosc, srunner/examples/LaneChangeSimple.xosc, srunner/examples/OscControllerExample.xosc, srunner/examples/PedestrianCrossingFront.xosc, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenariomanager/actorcontrols/actor_control.py, srunner/scenariomanager/actorcontrols/basic_control.py, srunner/scenariomanager/actorcontrols/external_control.py, srunner/scenariomanager/actorcontrols/npc_vehicle_control.py, srunner/scenariomanager/actorcontrols/pedestrian_control.py, srunner/scenariomanager/actorcontrols/vehicle_longitudinal_control.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/scenario_manager.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenarios/open_scenario.py, srunner/tools/openscenario_parser.py, srunner/utilities/code_check_and_formatting.sh
Added controller support for OSC
- Controllers are implemented in srunner.scenariomanager.actorcontrols
- Provided several example controllers for vehicles and pedestrians
* NpcVehicleControl using CARLA LocalPlanner
* PedestrianControl
* VehicleLongitudinalControl only modifying throttle
* ExternalControl to allow using manual_control.py
- Extended scenario atomics to handle new controls
* ChangeActorControl: Change actor controller
* ChangeActorTargetSpeed: Change target speed (longitudinal control)
* ChangeActorWaypoints: Change waypoints
* ChangeActorLateralMotion: Change lateral control
* UpdateAllActorControls: Execute one control loop step for all actors
- Not yet supported:
* Activation/Deactivation of a controller
Updated synchronous mode handling to resolve conflicts with …
=> Added actor controllers for OSC

Docs/CHANGELOG.md, Docs/openscenario_support.md, srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py, srunner/scenariomanager/weather_sim.py, srunner/tools/openscenario_parser.py
Added TimeOfDayComparison atomic trigger condition, which also allows the support TimeOfDayCondition for OSC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/551)
=> Added support for OSC's TimeOfDayCondition

srunner/scenariomanager/actorcontrols/actor_control.py
If a controller is specified as a python module, use last section after '.' as classname.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/560)
=> Fix module loading for ExternalControl

Docs/CHANGELOG.md, srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/scenarios/follow_leading_vehicle.py
Fixed a bug causing FollowLeadingVehicle and FollowLeadingvehicleWithObstacle scenarios to not properly end. This was caused by the StandStill behavior, which by default, needs a duration to succeed (and it wasn't being passed)
Also fixes a bug at CollisionTest causing it to ignore multiple hits with scene objects (as their id was always 0.
* **CARLA version:** 0.9.9.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/564)
=> Fixed FollowLeadingVehicle ending bug + CollisionTest bug

Docs/CHANGELOG.md, srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/tools/openscenario_parser.py
Added a new *EndofRoadTest* atomic criterion, which allows the support of _EndOfRoadCondition_
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/570)
=> Added support of OSC's EndOfRoadCondition

srunner/scenariomanager/carla_data_provider.py
This PR has two minor changes:
1) When creating the actor blueprint, the color will be left as default if the vehicle has the *hero* tag. This is done to be in tandem with all the new CARLA visual materials which will always feature a black linkoln (its default color) 
2) The background activity has been made deterministic, and will now spawn the same cars at the same locations.
* **CARLA version:** 0.9.9.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/569)
=> Default hero color + deterministic background activity

Docs/CHANGELOG.md, srunner/scenarioconfigs/openscenario_configuration.py
Previously, all entities were passed in the order they are listed
in the XOSC file, which could cause problems if the position of the
first entity is relative to the second entity.
The parsing of the initial positions was reworked to allow relative
positions to any other entity.
Checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/578)
=> Enabled using relative positioning for all entities in OSC

Docs/CHANGELOG.md, Docs/openscenario_support.md, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py, srunner/scenarios/object_crash_vehicle.py, srunner/tools/openscenario_parser.py
Added support for OSC's TimeHeadwayCondition, which uses *InTimeToArrivalToVehicle*.
Added support of *alongRoute* attribute (calculate the distance taking into account the driving lanes) for *RelativeDistanceCondition* and *TimeToCollisionCondition*
For all these behaviors, the *freespace* argument (used to check the bounding box, not only the reference points) is still unsupported
Changes:
- **calculate_distance** at *atomic_behaviors* now has a global_planner argument, used to calculate the "route distance".
- **InTriggerDistanceToOSCPosition**: added *along_route* argument.
- **InTimeToArrivalToOSCPosition**: added *along_route* argument.
- **InTimeToArrivalToVehicle**: added *along_route* argument. Swapped the places of *actor* and *other_actor* arguments, to match the other …
=> Added support for TimeHeadwayCondition + alongRoute argument support

Docs/getting_scenariorunner.md, README.md, manual_control.py
- Changed the Docs to explain how to set up the environment variables for Windows
- The _default_font_ for the manual_control fails at Windows. Added a check so that it doesn't happen (copied the one at CARLA's manual_control).
Fixes  #580 #367
* **Platform(s):** Windows 10
Hopefully no copy paste errors happened when passing the commands to Linux
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/581)
=> Added Windows Docs and support for manual control

Docs/CHANGELOG.md, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py
Fixed bug with SyncArrival behavior causing the atomic to fail if the actor was destroyed during the simulation. To do so, a check has been placed before trying to apply the control
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/585)
=> Fixed bug with Sync Arrival

Docs/CHANGELOG.md, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/tools/openscenario_parser.py
The CustomCommandAction script can now be provided with a path
relative to the OSC scenario file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/590)
=> Fixed OSC CustomCommandAction with relativ paths

Docs/CHANGELOG.md, srunner/scenarios/basic_scenario.py
Attached controllers were not cleaned up correctly (i.e. reset() was never called).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/591)
=> Cleanup controllers

srunner/scenariomanager/carla_data_provider.py
When cleaning up the CarlaDataProvider, a check has been added to see if the actor is already dead. This speeds up the cleanup process in cases where the simulation crashes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/597)
=> Added alive check at CDP cleanup

srunner/scenariomanager/scenarioatomics/atomic_criteria.py
Removed the creation of some blackboard variables at the criteria used at routes. These were used at the leaderboard to print the results through the console, but that part has been remade and they are no longer needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/598)
=> Removed unused blackboard variables

Docs/CHANGELOG.md, srunner/scenariomanager/scenarioatomics/atomic_criteria.py
Divided a *waypoint.next()* call in two at the *RunningStopTest* to avoid breaking the simulation with ending roads
* **CARLA version:** current master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/607)
=> Fixed next waypoint bug at RunningStopTest

Docs/CHANGELOG.md, srunner/examples/CatalogExample.xosc, srunner/examples/FollowLeadingVehicle.xosc, srunner/examples/catalogs/EnvironmentCatalog.xosc, srunner/examples/catalogs/VehicleCatalog.xosc, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenarios/open_scenario.py, srunner/tools/openscenario_parser.py
Reworked OSC Parameter Handling
- Added support for ParameterAssignment
- Added support for parameters inside OSC Catalogs
(Note: by OSC 1.0 definition all parameters used in catalogs must be
defined within the catalog)
- ParameterDeceleration must no longer start with '$', only when the
parameter is used, a '$' has to be added. This change was required to be
aligned with the standard.
- Updated example scenarios
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/605)
=> Fixed use of OSC Parameters within OSC Catalogs

Docs/CHANGELOG.md, scenario_runner.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py
I'm creating this WIP PR to discuss what's the best way to set the traffic manager port so that one can run multiple simulators and scenarios on a single machine. 
To make this change, I've started from the points where the code invokes `get_trafficmanager()` or `SetAutoPilot` and propagated up the traffic manager port. However, it looks like this requires the port to be passed to BasicScenario, and hence to the constructors of all the different scenarios. What do you think, is this the right approach or is there a more contained way to make this change?
Fixes #  
--- …
=> [WIP] Expose traffic manager port.

Docs/CHANGELOG.md, srunner/examples/CatalogExample.xosc, srunner/examples/catalogs/VehicleCatalog.xosc, srunner/tools/openscenario_parser.py
Fixed a bug that led to the problem that all instances of a catalog
element used the same parameter value.
Fixes #619 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/620)
=> Fixed OSC parameter usage of multiple catalog instances

srunner/tools/openscenario_parser.py
Having 2+ parameters, where one parameter included the name of one of the others
(e.g. xy and xyz), resulted in a corrupted parameter-value replacement. This
commit should fix this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/622)
=> Fixed OSC Parameter issue

Docs/CHANGELOG.md, requirements.txt
This is explicitly used by srunner/scenariomanager/carla_data_provider.py
When installing in a sandboxed environment that pulls in requirements.txt and executing the follow lead vehicle scenario:
```
Traceback (most recent call last):
File "/mnt/mervin/workspaces/devel/scenarios/scenario_runner/scenario_runner.py", line 33, in <module>
from srunner.scenarioconfigs.openscenario_configuration import OpenScenarioConfiguration
File "/mnt/mervin/workspaces/devel/scenarios/scenario_runner/srunner/scenarioconfigs/openscenario_configuration.py", line 27, in <module>
from srunner.scenariomanager.carla_data_provider import CarlaDataProvider  # workaround
File "/mnt/mervin/workspaces/devel/scenarios/scenario_runner/srunner/scenariomanager/carla_data_provider.py", line 18, in <module>
from six import …
```
=> Add 'six' to the requirements

Docs/CHANGELOG.md, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/tools/openscenario_parser.py
For RelativeTargetSpeed `target_speed` value was not initialised as it was not possible to find this value before the event is triggered. so the `target_speed` is initialised to 0.0 when parsed.
When the ChangeActorTargetSpeed is initialised `target_speed` is set to reference actor speed.
Fixes   #632
* **Platform(s):**Ubuntu 18.04
* **Python version(s):**  2.7
* **CARLA version:**  0.9.9.4 & 0.9.10
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/639)
=> Fixed OSC RelativeTargetSpeed error

Docs/CHANGELOG.md, srunner/scenariomanager/scenarioatomics/atomic_criteria.py
Fixed a bug at *rotate_point* function inside RunningRedLightTest criteria causing vectors to not be rotated properly. This doesn't change the criteria, as all the vectors rotated had no *y* component.
Fixes #643
* **Platform(s):** Ubutu 18.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/644)
=> Rotate point bug

srunner/scenarios/object_crash_vehicle.py
**DO NOT MERGE UNTIL CARLA 0.9.10.1 IS RELEASED**
There has been a fix at the CARLA main repository that has fixed a walkers bug causing the *set_simulate_physics* to wrongly interact with them.
This affects the DynamicObjectCrossing scenario as it was unintentionally moving walkers without physics. As this is no longer possible, this has to be fixed. Now, when the pedestrian are moved to the ground level (from z=-500), the physics are correctly set up to True (ActorTransformSetter sets physics to True by default).
* **Platform(s):** 3.6
* **Python version(s):** 18.04
This might happen at other places which haven't been detected and changed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Changed walker physics

Docs/CHANGELOG.md, srunner/autoagents/agent_wrapper.py, srunner/autoagents/autonomous_agent.py, srunner/autoagents/sensor_interface.py
Currently the **CARLA pipeline has a problem in sync mode** causing the simulation to not wait for the sensors to be rendered (as this is done in parallel to the main thread). Therefore, a **sensor barrier** is needed at the client side to ensure that the simulation is blocked until all sensor data is rendered.
Regarding SR, the **sensor data is now stored at a **Queue**** instead of a dictionary. Queue's are optimized to insert and remove elements, which is perfect for this use-case. When the data is received, the Queue is filled and the agents asks for the data, it is removed from the queue. Additionally, the *get* function is a blocking one, allowing the client to block the simulation in case the queue has some missing elements.
**Removed *all_sensors_ready*** function as its …
=> Added sensor barrier to agents

Docs/CHANGELOG.md, srunner/scenarioconfigs/openscenario_configuration.py, srunner/tools/openscenario_parser.py
OpenSCENARIO based scenarios that do not use an EnvironmentAction
inside the Storyboard Init part, are no longer throwing an exception.
First part to address #655 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/656)
=> Fixed exception when using OSC scenarios without environment init

Docs/CHANGELOG.md, scenario_runner.py
Fixes #657
Synchronous TM is now only activated when the simulation is also synchronous, as it was causing the TM to not be correctly updated
* **CARLA version:** 0.9.10.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/662)
=> Fix TM not being updated at async simulations

Docs/index.md
- The formatting of index in the landing page of the docs is not working. Local visualization and RtD final version do not correspond.
- Fixed by using only HTML. 
* **Platform(s):** Ubuntu 18.04.4
* **Python version(s):** 3.6.9
- localhost may still be different than RtD version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/664)
=> sergi-e/docs-index-fix

Docs/CHANGELOG.md, srunner/scenarios/open_scenario.py, srunner/tools/openscenario_parser.py
The check provides a Warning, if the name of a story, act, maneuvergroup or maneuver
(e.g. story_name->act_name->maneuvergroup_name) appears more than once.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/659)
=> Added check to ensure names in OSC are unique

srunner/tools/openscenario_parser.py
Fixed an issue introduced 3 commits before (#656)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/668)
=> Fixed handling of Weather in OSC

Docs/CHANGELOG.md, scenario_runner.py
On shutdown it could happen that sync mode remained active, causing issues on next startup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/669)
=> Fixed shutdown issue in ScenarioManager causing problems in sync mode

Docs/CHANGELOG.md, Docs/openscenario_support.md, srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py, srunner/tools/openscenario_parser.py
Description
A new class ```InTimeToCollisionToVehicle``` is added to support ```TimeToCollisionCondition``` tag for dynamic actors.
The formula used for TimeToCollision calculation in previous Implementation is :
```
Relative Distance = Distance between centre location of two actors.
TimeToCollision = (2 * Relative Distance ) /  relative velocity of two actors
```
The formula used for TimeToCollision calculation in current implementation is :
```
Relative Distance = Distance between centre location of two actors.
When "freespace" is true:
TimeToCollision = (Relative Distance - half of length of actor1 -  half of length of actor2 ) / relative velocity of two actors.
When "freespace" is false:
TimeToCollision = Relative Distance  / relative velocity of two actors.
```
The modified …
=> Defined a new class for TimeToCollisionCondition along with freespace implementation

Docs/CHANGELOG.md, srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py
Currently, while vehicles and walkers have bounding boxes, all other objects such as static props or traffic signs don't. This was causing an exception when InTimeToArrivalToVehicle was being used to check for such objects. An additional condition has been placed, to avoid such exception.
Fixes #678
* **Platform(s):** Ubutnu 18.04
* **CARLA version:** 0.9.10.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/679)
=> Fixed InTimeToArrivalToVehicle bug with static objects

Docs/CHANGELOG.md, Docs/openscenario_support.md, srunner/scenariomanager/actorcontrols/npc_vehicle_control.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/tools/openscenario_parser.py
When using routing options (routeStrategy) for route waypoints in OSC,
shortest and fastest will be treated differently.
Shortest = direct connection between A and B
Others = shortest path along the road network from A to B
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/677)
=> Added support for OSC routing options

srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/tools/openscenario_parser.py
Fixed a bug at the last commit causing *AcquirePositionAction* of OSC to crash. The new *ChangeActorWaypoints* already has a global route planner, therefore the *ChangeActorWaypointsToReachPosition* behavior can be completely removed.
Changed some parts of the code from location to waypoint location at the *ChangeActorWaypoints*. This fixes the behaviour when the actor was initially far away from the center of the lane
* **CARLA version:** 0.9.10.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/687)
=> Fixed AcquirePositionAction

Docs/CHANGELOG.md, scenario_runner.py, srunner/scenarioconfigs/openscenario_configuration.py
Using the "CARLA:" prefix in the OSC description caused broken result files
under Windows. Therefore, the internal handling of the scenario name was modified
to enable writing the output files under Windows and Linux.
Fixes #682
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/691)
=> Fixed writing result files with OSC under Windows

Docs/index.md, Docs/openscenario_support.md
Fix to the tables at the OSC docs, causing them to have additional rows than expected
(current tables below)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/716)
=> Fixed tables at OSC docs

Docs/CHANGELOG.md, Docs/getting_started.md, scenario_runner.py, srunner/scenarioconfigs/openscenario_configuration.py, srunner/tools/openscenario_parser.py
Checklist:
New:
Added `--openscenarioparams` parameter to scene_runner, which overwrites the global ParameterDeclaration.
Syntax: 
```bash
python scenario_runner.py --openscenario <path/to/xosc-file> --openscenarioparams 'param1: value1, param2: value2'
```
Change: 
openscenario_parser.py: `additional_parameter_dict` argument of set_parameters overwrites those found in XML, in case of conflict.
* **Platform(s):*Ubuntu 18.04*
* **Python version(s):*2, 3*
openscenario_parser.py: `additional_parameter_dict` argument of set_parameters overwrites those found in XML, in case of conflict.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/736)
=> Overwrite ParameterDeclarations from CLI arguments.

Docs/CHANGELOG.md, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenariomanager/actorcontrols/carla_autopilot.py, srunner/scenariomanager/actorcontrols/simple_vehicle_control.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenarios/open_scenario.py
* Added controller using CARLA's autopilot (in replacement for ActivateControllerAction)
* Added support for storyboards with multiple stories
* Extended SimpleVehicleController (OSC) to handle traffic lights, turn on brake lights and use reasonable acceleration/deceleration
* Improved reloading of OpenDRIVE maps
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/739)
=> Several improvements to OpenSCENARIO support

Docs/CHANGELOG.md, srunner/scenarioconfigs/openscenario_configuration.py, srunner/scenariomanager/actorcontrols/simple_vehicle_control.py, srunner/scenariomanager/actorcontrols/visualizer.py, srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/tools/openscenario_parser.py
Fixes #727 
Past behavior:
A lane change in OSC was always set to cover 1000m, if there was no proper end condition set.
New behavior:
A lane change in OSC covers now only 10m on the new lane. To avoid that a vehicle stops immediately after, the behavior returns with success but provides waypoints for another 200 meters to allow the vehicle to continue moving.
* **Python version(s):** 3.8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/741)
=> Fixed never ending lane change maneuver in OSC

Docs/CHANGELOG.md, scenario_runner.py, srunner/scenarioconfigs/openscenario_configuration.py
Before enforcing a reload of the CARLA map when using OpenSCENARIO
the currently loaded map is compared with the new map. This comparison
was reworked to enforce that both maps start with the '<OpenDRIVE>' start tag:
- Perform map string comparison only for content after <OpenDRIVE> tag
- Load OpenDRIVE map using vertex_distance etc. parameters
Reworked handling of TrafficManager inside ScenarioRunner to improve
startup time:
- Moved TrafficManager code from constructor to _load_and_run_scenario after updating the world
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/752)
=> Improved reloading of OpenDRIVE maps in OSC

Docs/CHANGELOG.md, requirements.txt, srunner/scenariomanager/scenario_manager.py, srunner/scenariomanager/watchdog.py
The watchdog has been improved:
- It can now be paused and resumed
- The old watchdog's *update* method closed the current thread and started another one. That behavior has been updated so that everything is done at the same thread.
- Added checks to see if the watchdog has started before trying to manipulate it. This was causing errors when trying to stop a non-started watchdog. 
Other changes:
- Added [`simple-watchdog-timer`](https://github.com/hjortlund/simple_watchdog_timer) to the requirements, as it is the library used to implement the new watchdog
- Removed unused function `get_running_status()` at *scenario_manager.py*.
- `stop_scenario()` at *scenario_manager.py* now, if needed, additionally stops the watchdog (needed due to the new watchdog behavior).
* **Platform(s):** Ubuntu …
=> Updated watchdog

README.md
This change updates the `CARLA Challenge` references in the readme to correctly point to the Leaderboard website and repository.
Platform(s): Ubuntu 18.04
Python version(s): 3.7
Unreal Engine version(s): 4.26
CARLA version: 0.9.11 (current dev)
None. This is a documentation correction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/763)
=> Updated README to link Challenge to Leaderboard

srunner/scenariomanager/result_writer.py
The generated XML result file is ill formatted. 
I have discovered the problem when I tried to generate HTML version of results from XML generated by scenario runner. 
Input: 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="2" failures="1" disabled="0" errors="0" timestamp="2021-06-14 07:45:16" time="44.30" name="Simulation" package="Scenarios">
<testsuite name="AsWaypointFollower_2" tests="2" failures="1" disabled="0" errors="0" time="44.30">
<testcase name="CollisionTest_asystems.vez10_171" status="run" time="0" classname="Scenarios.AsWaypointFollower_2">
<failure message="CollisionTest"  type=""><!\[CDATA\[
Actual:   1
Expected: 0
Exact Value: CollisionTest = 1\]\]></failure>
</testcase>
<testcase name="Duration" status="run" time="44.29674530029297" …
```
=> Removed illegal escape on [] around CDATA in junit xml.

Docs/CHANGELOG.md, srunner/tools/openscenario_parser.py
#Fixes #767
@sagar-g-v : I think changing the sign only for t < 0 is not correct, and has to be inverted always when using an common XODR coordinate system. Do you agree?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/771)
=> Fixed OSC LaneOffset sign handling

srunner/tools/openscenario_parser.py
Simple fix to make sure that traffic_lights can be read using the id as well as positions. The code was checking equality between int (returned by the actor.id) and string and therefore not working correctly. Added the conversion of the id form the osc to int rather than string. 
I just added int() around the traffic_light_id (tf_id) from the osc file.
Fixes #  
* **Platform(s): ubuntu 18.04**
* **Python version(s): 3.7.5**
* **Unreal Engine version(s):4.24**
* **CARLA version:0.9.11**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/774)
=> add int() around id to make eq work in traffic_light identifier when reading from openscenario

manual_control.py
I added two more arguments to `manual_control.py`:
- `--rolename`
- `--keep_ego_vehicle`
The `rolename` argument can be used to search for ego vehicles with role names other than `hero`. This is especially required when running the scenario runner with the arguments `--waitForEgo` and `--openscenario`: this specific setting only works if the already existing vehicle has the role name `ego_vehicle` (instead of `hero`) and if the corresponding entity in the XOSC file is called `ego_vehicle` (`<ScenarioObject name="ego_vehicle">...</ScenarioObject>`).
The `keep_ego_vehicle` argument can be set in order to prevent the destruction of the ego vehicle after the termination of the `manual_control.py` script.
* **Python version(s):** 3.8
* **Unreal Engine …
=> Add more parameters

requirements.txt
The current shapely version was creating conflicts with python 3.8, which is solved upgrading from 1.6.4 to 1.7.1
* **Python version(s):** 3.6, 3.7
* **CARLA version:** 0.9.12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/797)
=> Updated Shapely version

srunner/tools/openscenario_parser.py
Fixed bug that ignores orientation provided by OpenScenario file for RelativeRoadPosition.
* **Python version(s):** 2.7.17
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/806)
=> Fixed rotation when using relative road position

Docs/CHANGELOG.md, scenario_runner.py
The *finished* attribute was added to avoid multiple cleanups of the simulation. However, this parameter wasn't being reset on repetitions, causing them to crash if 3 or more were run
Fixes #798
* **CARLA version:** 0.9.12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/812)
=> Fixed repetition crash

srunner/scenarios/actor_flow.py, srunner/scenarios/opposite_vehicle_taking_priority.py, srunner/scenarios/signalized_junction_left_turn.py, srunner/scenarios/signalized_junction_right_turn.py
Fixed bug with new JunctionScenrioManager
* **Platform(s):** Ubutnu 18.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/873)
=> Fixed bug at jucntions scenarios

srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/scenarios/background_activity.py
RouteCompletionTest was returning two traffic events (used at the leaderboard's statistics manager). On of them has been improved, and the other one was removed, as it was unused
The backgroundActivity will now also filter vehicles by wether or not they can turn on their lights
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/877)
=> Improved traffic event handling for RouteCompletionTest

srunner/scenarios/route_scenario.py
Fixed a bug that was causing scenario specific criteria to stop the simulation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/898)
=> Added Idle

srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/scenariomanager/timer.py, srunner/scenariomanager/traffic_events.py, srunner/scenarios/actor_flow.py, srunner/scenarios/construction_crash_vehicle.py, srunner/scenarios/cross_bicycle_flow.py, srunner/scenarios/invading_turn.py, srunner/scenarios/parking_exit.py, srunner/scenarios/route_obstacles.py, srunner/scenarios/signalized_junction_left_turn.py, srunner/scenarios/signalized_junction_right_turn.py, srunner/scenarios/vehicle_opens_door.py
Some of the new scenario could block the ego forever. A timeout has been added to their behavior tree that, after a set amount of time, will stop the scenario, allowing the ego to continue, but penalising the stack, reducing its score (at the Leaderboard).
These scenarios are:
- The `ParkingExit`
- Obstacle scenario that require a lane change (i.e `Accident`, `Construction`, ...)
- Junction scenarios with actor flows (`CrossingBicycleFlow`, `SignalizedJucntionLeftTurn`, ...)
- Highway entry / exits (`EnterActorFlow`, `HighwayExit`, ...)
--- …
=> Added scenario timeouts

srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/scenariomanager/traffic_events.py
With the addition of live results at the LB, the OutsideRouteLanesTest has been modified to have its traffic event track its value on realtime, instead of being created at the end. The behavior remains unchanged
* **Platform(s):** Ubutnu18.04
* **Unreal Engine version(s):** CARLA's 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/920)
=> Minor changes to OutsideRouteLanes event

srunner/tools/openscenario_parser.py
Updated is_literal in openscenario_parser.py so that it check for Euler's number.
OpenScenario files exported from RoadRunner contains values with Euler's number.
OpenScenario files exported from RoadRunner contains values with Euler's number. The check in the parser didn't check for Euler's number. Now it does.
Fixes #  
* **Platform(s):** Windows 10
* **Python version(s):** 3.8.18
* **Unreal Engine version(s):** 4.26.2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/1028)
=> Check for Euler's number

srunner/scenarioconfigs/openscenario_configuration.py
Using OpenDrive maps with the schema argument in the root element <OpenDRIVE> could not been read. 
* **Platform(s):** Ubuntu 20.04, Ubuntu 18.04
* **Unreal Engine version(s):** 4.26 
Theoretical it would allow multiple arguments or a missing  ">"  and could be better solved with a regex but not sure if that would be overkill.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/967)
=> Fix for OpenDrive maps with schema argument

srunner/scenarioconfigs/osc2_scenario_configuration.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/1074)
=> Remove extra lines

srunner/scenariomanager/carla_data_provider.py
Cherry-pick PR #1068 onto master
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/1075)
=> Fix: wrong initial transform when using request_new_batch_actors (#1068)

Docs/CHANGELOG.md, srunner/scenariomanager/carla_data_provider.py
Currently when one wants to spawn an Actor from a blueprint this is only possibly via the World object.
There is no addition to the hidden `CarlaDataProvider._carla_actor_pool` and `CarlaDataProvider.register_actor` must be called manually.
This PR adds an analogue version, which always adds the actor to the pool for cleanup and if not specified otherwise calls register_actor on Vehicles and Walkers.
```py
def spawn_actor(bp, spawn_point, must_spawn=False, track_physics=None, attach_to=None, attachment_type=carla.AttachmentType.Rigid)
```
* **Python version(s):** Python 3.10
Possibly favor a second `.try_spawn_actor` instead of `must_spawn=False`.
- - - …
=> [Feature] Blueprint-based spawn_actor function for CarlaDataProvider

scenario_runner.py
distutils LooseVersion and pkg_resources are deprecated and not available in later python versions.
This introduces two commits fixing these deprecation for Python3.8+ while maintaining functionality for Python3.7 and before.
NOTE: Reverting the second commit removes the backward compatibility to Python3.7, as `importlib.metadata` is introduced in Python3.8.
Fixes #
* **Python version(s):** 3.7, 3.8, 3.10
* **CARLA version:** 0.9.14 (fails as expected), 0.9.15
The second commit bloats the code a bit and should be reverted when python3.7 should not be supported anymore removing pkg_resources entirely.
- - - …
=> Backward compatible upgrade to fix deprecation warnings concerning LooseVersion and pkg_resources for Python3.8+

scenario_runner.py
This is is slight modification of #1058 for the leaderboard-2.0 branch with adjustments for Carla 0.9.12.
---
distutils LooseVersion and pkg_resources are deprecated and not available in later python versions.
This introduces two commits fixing these deprecation for Python3.8+ while maintaining functionality for Python3.7.
NOTE: Reverting the second commit removes the backward compatibility to Python3.7, as `importlib.metadata` is introduced in Python3.8.
* **Python version(s):** 3.7, 3.8, 3.10
* **CARLA version:** 0.9.14 (fails as expected), 0.9.15
The second commit bloats the code a bit and should be reverted when python3.7 should not be supported anymore removing pkg_resources entirely.
- - - …
=> [Leaderboard 2.0] Backward compatible upgrade to fix deprecation warnings concerning LooseVersion and pkg_resources for Python3.8+ (#1058 analog)

scenario_runner.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/1081)
=> Remove version redundancy

srunner/tools/openscenario_parser.py
There was a typo in function "get_traffic_light_from_osc_name" in openscenario_parser.py, which was trying to access "CCarlaDataProvider" insted of "CarlaDataProvider". Typo fixed.
This is the typo.
Runs without problems after fixing the typo.
* **Platform(s):** Win11
* **Python version(s):** 3.8.10
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/1118)
=> Fixed a typo in openscenario_parser.py

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/1129)
=> Link documentation in README

srunner/scenarios/route_scenario.py
Fixed an issue brought by [commit](https://github.com/carla-simulator/scenario_runner/commit/5828e5913d7bace51de56d8516ca6c6190213acb), mentioned in PR [1136](https://github.com/carla-simulator/scenario_runner/pull/1136). This is an alternative of that PR that instead of reverting the lgoa gents, adds the missing information to the blackboard variable.
* **Platform(s):** UBuntu 20.04
* **Python version(s):** 3.8
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/1141)
=> Fixed scenario triggerer

no_rendering_mode.py, srunner/scenariomanager/carla_data_provider.py, srunner/scenariomanager/scenarioatomics/atomic_criteria.py, srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py, srunner/scenarios/maneuver_opposite_direction.py, srunner/tools/scenario_helper.py
Waypoint.is_intersection is deprecated since CARLA 0.9.6. This PR updates the locations where it is used.
https://github.com/carla-simulator/carla/blob/c097d7acf123824e7f032f20fe6d3fd9e7bfa4cc/CHANGELOG.md?plain=1#L448
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/1114)
=> Updated deprecated Waypoint.is_intersection to is_junction

srunner/scenariomanager/carla_data_provider.py
* **Python version(s):** Python 3.7 and 3.10
---
When using `CarlaDataProvider.get_velocity / transform / location(actor)` the lookup function loops over all dict keys and compares the actor id of each key against the argument's id. Comparing all ids is necessary, as different python instances of the same actor have different hashes, but inefficient if the argument is a present key.
This PR adds a best-case lookup before and checks if the actor a present key before it falls back to the slower loop over all actors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/1098)
=> Speed up information retrieval

Docs/CHANGELOG.md, srunner/scenariomanager/actorcontrols/simple_vehicle_control.py, srunner/scenarios/open_scenario.py, srunner/tools/openscenario_parser.py, srunner/tools/util.py
Checklist:
distutils are no longer available in Python 3.12. Therefore, we copy the strtobool function from distutils to our own module. This is in line with https://peps.python.org/pep-0632/#migration-advice.
* **Platform(s):** Linux
* **Python version(s):** 3.12
Hopefully none.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/1121)
=> Don't depend on distutils

Docs/CHANGELOG.md, srunner/scenarios/osc2_scenario.py
Checklist:
This fixes warnings like the one below:
.../srunner/scenarios/osc2_scenario.py:515: SyntaxWarning: invalid escape sequence '\W'
expression_value = re.split("\W+", option)
These were introduced in Python 3.12. See https://docs.python.org/3.12/reference/lexical_analysis.html#escape-sequences.
* **Platform(s):** Linux
* **Python version(s):** 3.12
Hopefully none. r-strings are available even in Python 2.6, so this should work even with older Python versions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/scenario_runner/1122)
=> osc2_scenario: Fix SyntaxWarnings
